#!/usr/bin/env bash
# regression_ssim.sh — SSIM regression tests for unscan
#
# Runs the unscan binary against known test cases and checks that
# SSIM scores stay above established thresholds. Catches regressions
# in the verify pipeline (rendering, blur, multi-scale, SSIM math).
#
# Usage:
#   ./tests/regression_ssim.sh              # uses ./target/release/unscan
#   UNSCAN=./target/debug/unscan ./tests/regression_ssim.sh
#
# Prerequisites:
#   - Built binary (cargo build --release)
#   - EB Garamond 12 at /usr/share/fonts/opentype/ebgaramond/EBGaramond12-Regular.otf
#   - python3 + Pillow (for generating test fixtures)
#   - pdftoppm (poppler-utils)
#   - ImageMagick convert

set -uo pipefail

UNSCAN="${UNSCAN:-./target/release/unscan}"
TESTDIR="test-docs"
PASS=0
FAIL=0
SKIP=0

red()   { printf '\033[1;31m%s\033[0m\n' "$*"; }
green() { printf '\033[1;32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[1;33m%s\033[0m\n' "$*"; }

# ── Generate test fixtures if missing ─────────────────────────────────

generate_fixtures() {
    local font="/usr/share/fonts/opentype/ebgaramond/EBGaramond12-Regular.otf"
    if [ ! -f "$font" ]; then
        yellow "SKIP: EB Garamond 12 not installed — cannot generate fixtures"
        return 1
    fi

    # punch-hires.pdf: 600 DPI source, "punchcutter" at 120px
    # pdftoppm at default 300 DPI → 900x120, font ~60px effective
    if [ ! -f "$TESTDIR/punch-hires.pdf" ]; then
        echo "  Generating punch-hires.pdf..."
        python3 -c "
from PIL import Image, ImageFont, ImageDraw
import subprocess
font = ImageFont.truetype('$font', 120)
img = Image.new('L', (1800, 240), 255)
ImageDraw.Draw(img).text((0, 60), 'punchcutter', font=font, fill=0)
img.save('/tmp/_punch-hires.png')
subprocess.run(['convert', '/tmp/_punch-hires.png', '-density', '600',
                '$TESTDIR/punch-hires.pdf'], check=True)
"
    fi

    # punch-garamond.pdf: 200 DPI, same word
    if [ ! -f "$TESTDIR/punch-garamond.pdf" ]; then
        echo "  Generating punch-garamond.pdf..."
        python3 -c "
from PIL import Image, ImageFont, ImageDraw
import subprocess
font = ImageFont.truetype('$font', 120)
img = Image.new('L', (1800, 240), 255)
ImageDraw.Draw(img).text((0, 60), 'punchcutter', font=font, fill=0)
img.save('/tmp/_punch-garamond.png')
subprocess.run(['convert', '/tmp/_punch-garamond.png', '-density', '200',
                '$TESTDIR/punch-garamond.pdf'], check=True)
"
    fi

    # punch-gold.png: native 60px, no pdftoppm (gold standard — same FreeType)
    if [ ! -f "$TESTDIR/punch-gold.png" ]; then
        echo "  Generating punch-gold.png..."
        python3 -c "
from PIL import Image, ImageFont, ImageDraw
font = ImageFont.truetype('$font', 60)
img = Image.new('L', (900, 120), 255)
ImageDraw.Draw(img).text((100, 30), 'punchcutter', font=font, fill=0)
img.save('$TESTDIR/punch-gold.png')
"
    fi

    # punch-100dpi-big.pdf: 600 DPI source with 40pt text, loaded at 100 DPI
    # pdftoppm at 100 DPI → 850x300, font ~55px effective
    if [ ! -f "$TESTDIR/punch-100dpi-big.pdf" ]; then
        echo "  Generating punch-100dpi-big.pdf..."
        python3 -c "
from PIL import Image, ImageFont, ImageDraw
import subprocess
font = ImageFont.truetype('$font', 333)  # 40pt at 600 DPI
img = Image.new('L', (5100, 1800), 255)
ImageDraw.Draw(img).text((600, 600), 'punchcutter', font=font, fill=0)
img.save('/tmp/_punch-100dpi-big.png')
subprocess.run(['convert', '/tmp/_punch-100dpi-big.png', '-density', '600',
                '$TESTDIR/punch-100dpi-big.pdf'], check=True)
"
    fi

    # specimen-clean-raster.pdf: generated by gen-specimen.py
    if [ ! -f "$TESTDIR/specimen-clean-raster.pdf" ]; then
        echo "  Generating specimen-clean-raster.pdf..."
        if [ -f "$TESTDIR/gen-specimen.py" ]; then
            python3 "$TESTDIR/gen-specimen.py"
        else
            yellow "  SKIP: gen-specimen.py not found"
            return 1
        fi
    fi

    return 0
}

# ── Test runner ───────────────────────────────────────────────────────

# Run unscan, extract SSIM for the matched font, compare to threshold.
# Args: test_name input_file threshold [extra_args...]
check_ssim() {
    local name="$1" input="$2" threshold="$3"
    shift 3
    local extra_args=("$@")

    if [ ! -f "$input" ]; then
        yellow "SKIP $name — $input not found"
        SKIP=$((SKIP+1))
        return
    fi

    local output
    output=$($UNSCAN "$input" -o /dev/null \
        --min-font-confidence 0.0 --min-ocr-confidence 0 --min-verify-ssim 0.0 \
        "${extra_args[@]}" 2>&1)

    # Extract SSIM from "ssim=0.968" pattern
    local ssim
    ssim=$(echo "$output" | grep -oP 'ssim=\K[0-9.]+' | head -1)

    if [ -z "$ssim" ]; then
        red "FAIL $name — no SSIM score found in output"
        echo "     Output: $(echo "$output" | grep -i "punchcutter\|kept as raster\|no confident" | head -3)"
        FAIL=$((FAIL+1))
        return
    fi

    # Compare (bash can't do float comparison, use awk)
    local passed
    passed=$(awk "BEGIN { print ($ssim >= $threshold) ? 1 : 0 }")

    if [ "$passed" -eq 1 ]; then
        green "PASS $name — SSIM=$ssim (threshold $threshold)"
        PASS=$((PASS+1))
    else
        red "FAIL $name — SSIM=$ssim < threshold $threshold"
        FAIL=$((FAIL+1))
    fi
}

# Check vectorized line count from specimen run.
# Args: test_name input_file min_vectorized [extra_args...]
check_vectorized_count() {
    local name="$1" input="$2" min_count="$3"
    shift 3
    local extra_args=("$@")

    if [ ! -f "$input" ]; then
        yellow "SKIP $name — $input not found"
        SKIP=$((SKIP+1))
        return
    fi

    local output
    output=$($UNSCAN "$input" -o /dev/null --overlay "${extra_args[@]}" 2>&1)

    local count
    count=$(echo "$output" | grep -oP 'Text lines vectorised:\s+\K[0-9]+' | head -1)

    if [ -z "$count" ]; then
        red "FAIL $name — could not parse vectorized count"
        FAIL=$((FAIL+1))
        return
    fi

    if [ "$count" -ge "$min_count" ]; then
        green "PASS $name — $count vectorized (min $min_count)"
        PASS=$((PASS+1))
    else
        red "FAIL $name — $count vectorized < min $min_count"
        FAIL=$((FAIL+1))
    fi
}

# Check that the correct font family is matched.
# Args: test_name input_file expected_font_substr [extra_args...]
check_font_match() {
    local name="$1" input="$2" expected="$3"
    shift 3
    local extra_args=("$@")

    if [ ! -f "$input" ]; then
        yellow "SKIP $name — $input not found"
        SKIP=$((SKIP+1))
        return
    fi

    local output
    output=$($UNSCAN "$input" -o /dev/null \
        --min-font-confidence 0.0 --min-ocr-confidence 0 --min-verify-ssim 0.0 \
        "${extra_args[@]}" 2>&1)

    local matched_font
    matched_font=$(echo "$output" | grep '✓' | grep -oP '→ \K[^(]+' | head -1 | sed 's/ *$//')

    if echo "$matched_font" | grep -qi "$expected"; then
        green "PASS $name — matched '$matched_font'"
        PASS=$((PASS+1))
    else
        red "FAIL $name — matched '$matched_font', expected *$expected*"
        FAIL=$((FAIL+1))
    fi
}

# ── Main ──────────────────────────────────────────────────────────────

echo "unscan SSIM regression tests"
echo "Binary: $UNSCAN"
echo ""

if [ ! -x "$UNSCAN" ]; then
    red "ERROR: $UNSCAN not found or not executable"
    echo "Run: cargo build --release"
    exit 1
fi

echo "── Generating fixtures ──"
generate_fixtures || true
echo ""

echo "── SSIM threshold tests ──"
echo "  (correct font, correct word — SSIM must stay above threshold)"
echo ""

# Hires: 600 DPI source → 300 DPI scan. Established baseline: 0.968
check_ssim    "hires-ssim"     "$TESTDIR/punch-hires.pdf"       0.95

# 100 DPI: 600 DPI source → 100 DPI scan. Established baseline: 0.983
check_ssim    "100dpi-ssim"    "$TESTDIR/punch-100dpi-big.pdf"  0.95  --dpi 100

# Garamond 200 DPI. Established baseline: 0.908
check_ssim    "garamond-ssim"  "$TESTDIR/punch-garamond.pdf"    0.85

# Gold PNG: native 60px, no pdftoppm. Established baseline: 0.982
check_ssim    "gold-png-ssim"  "$TESTDIR/punch-gold.png"        0.95

echo ""
echo "── Font identification tests ──"
echo "  (must identify EB Garamond, not a wrong font)"
echo ""

check_font_match "hires-font"    "$TESTDIR/punch-hires.pdf"       "EBGaramond"
check_font_match "100dpi-font"   "$TESTDIR/punch-100dpi-big.pdf"  "EBGaramond"  --dpi 100
check_font_match "garamond-font" "$TESTDIR/punch-garamond.pdf"    "EBGaramond"
check_font_match "gold-png-font" "$TESTDIR/punch-gold.png"        "EBGaramond"

echo ""
echo "── Specimen vectorization test ──"
echo "  (full specimen must vectorize at least N lines)"
echo ""

# Specimen: 94 lines total, currently 94 vectorized. Floor at 90 to allow some variance.
check_vectorized_count "specimen-count" "$TESTDIR/specimen-clean-raster.pdf" 90

echo ""
echo "════════════════════════════════════"
printf "  PASS: %d  FAIL: %d  SKIP: %d\n" "$PASS" "$FAIL" "$SKIP"
echo "════════════════════════════════════"

if [ "$FAIL" -gt 0 ]; then
    exit 1
fi
exit 0
