//! Specimen accuracy — 300 dpi, anti-aliased.
//!
//! Runs unscan with --audit against the AA-rasterized specimen, then
//! invokes tools/char-misses.py to compare each matched font against the
//! vector PDF's spatial ground truth via PyMuPDF.
//!
//! The specimen is generated by t55_specimen_gen; this test will also call
//! ensure_specimen() as a fallback so it works standalone.
//!
//! Run with:
//!   cargo test --test t60_specimen_accuracy -- --nocapture

mod common;

use common::{test_doc, ensure_index, unscan_bin};
use std::path::{Path, PathBuf};
use std::process::Command;

/// Minimum acceptable accuracy (hits / compared).
const MIN_ACCURACY: f64 = 0.90;

// ── Specimen setup ───────────────────────────────────────────────────

/// Ensure vector PDF + fontmap exist (delegates to gen-specimen.py).
fn ensure_specimen() {
    let vector_pdf = test_doc("font-timeline-specimen.pdf");
    let fontmap = test_doc("font-timeline-specimen-fontmap.json");

    if vector_pdf.exists() && fontmap.exists() {
        return;
    }

    eprintln!("[t60] Generating specimen via gen-specimen.py ...");
    let gen_script = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("test-docs")
        .join("gen-specimen.py");

    let output = Command::new("python3")
        .arg(&gen_script)
        .current_dir(Path::new(env!("CARGO_MANIFEST_DIR")).join("test-docs"))
        .output()
        .unwrap_or_else(|e| panic!("failed to run gen-specimen.py: {}", e));

    assert!(output.status.success(), "gen-specimen.py failed");
}

// ── Accuracy measurement ─────────────────────────────────────────────

struct AccuracyResult {
    hits: usize,
    misses: usize,
    unmatched: usize,
    skipped: usize,
    total: usize,
    compared: usize,
    accuracy: f64,
    report_path: PathBuf,
}

fn measure_accuracy() -> AccuracyResult {
    let vector_src = test_doc("font-timeline-specimen.pdf");
    let fontmap = test_doc("font-timeline-specimen-fontmap.json");

    // Use the AA raster — t55 creates this, but rasterize as fallback
    let raster = test_doc("font-timeline-specimen-rasterized.pdf");
    if !raster.exists() {
        eprintln!("[t60] Rasterizing 300dpi AA ...");
        assert!(
            common::rasterize_pdf(&vector_src, &raster, 300, true),
            "AA rasterization failed",
        );
    }

    let audit_dir = std::env::temp_dir().join("unscan-t60-audit-300dpi-aa");
    if audit_dir.exists() {
        let _ = std::fs::remove_dir_all(&audit_dir);
    }
    std::fs::create_dir_all(&audit_dir).expect("create audit dir");

    let output_pdf = audit_dir.join("out.pdf");

    // Run unscan with --audit and --fontmap
    let bin = unscan_bin();
    let mut cmd = Command::new(&bin);
    cmd.arg(&raster)
        .args(["-o", output_pdf.to_str().unwrap()])
        .args(["--audit", audit_dir.to_str().unwrap()])
        .env("RUST_LOG", "info");
    if fontmap.exists() {
        cmd.args(["--include-fontmap", fontmap.to_str().unwrap()]);
    }
    let output = cmd
        .output()
        .unwrap_or_else(|e| panic!("failed to run unscan: {}", e));

    assert!(output.status.success(), "unscan failed: {}",
        String::from_utf8_lossy(&output.stderr));

    assert!(audit_dir.join("audit.json").exists(),
        "audit.json not written");

    // Run char-misses.py
    let report_path = audit_dir.join("misses.html");
    let char_misses_py = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tools")
        .join("char-misses.py");

    let mut py_cmd = Command::new("python3");
    py_cmd.arg(&char_misses_py)
        .arg(&audit_dir)
        .arg(&vector_src)
        .args(["-o", report_path.to_str().unwrap()]);
    if fontmap.exists() {
        py_cmd.args(["--fontmap", fontmap.to_str().unwrap()]);
    }

    let py_output = py_cmd.output()
        .unwrap_or_else(|e| panic!("failed to run char-misses.py: {}", e));

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&py_output.stdout),
        String::from_utf8_lossy(&py_output.stderr),
    );
    assert!(py_output.status.success(), "char-misses.py failed:\n{}", combined);

    let (hits, misses, unmatched, skipped, total) = parse_summary(&combined);
    let compared = hits + misses;
    let accuracy = if compared > 0 { hits as f64 / compared as f64 } else { 0.0 };

    AccuracyResult { hits, misses, unmatched, skipped, total, compared, accuracy, report_path }
}

/// Parse: "Total: N  Hits: H  Misses: M (U unmatched)  Skipped: S"
fn parse_summary(output: &str) -> (usize, usize, usize, usize, usize) {
    let mut hits = 0;
    let mut misses = 0;
    let mut unmatched = 0;
    let mut skipped = 0;
    let mut total = 0;

    for line in output.lines() {
        if !line.contains("Total:") || !line.contains("Hits:") {
            continue;
        }
        for part in line.split_whitespace().collect::<Vec<_>>().windows(2) {
            match part[0] {
                "Total:" => total = part[1].parse().unwrap_or(0),
                "Hits:" => hits = part[1].parse().unwrap_or(0),
                "Misses:" => misses = part[1].parse().unwrap_or(0),
                "Skipped:" => skipped = part[1].parse().unwrap_or(0),
                _ => {}
            }
        }
        if let Some(pos) = line.find('(') {
            if let Some(end) = line[pos..].find(" unmatched)") {
                let n_str = &line[pos + 1..pos + end];
                unmatched = n_str.trim().parse().unwrap_or(0);
            }
        }
        break;
    }

    (hits, misses, unmatched, skipped, total)
}

// ── Tests ────────────────────────────────────────────────────────────

#[test]
fn specimen_font_accuracy_aa() {
    ensure_index();
    ensure_specimen();

    let r = measure_accuracy();

    eprintln!(
        "AA @ 300dpi: {}/{} = {:.1}% (threshold: {:.0}%)",
        r.hits, r.compared, r.accuracy * 100.0, MIN_ACCURACY * 100.0,
    );
    eprintln!(
        "  {} hits, {} misses ({} unmatched, {} wrong), {} skipped, {} total",
        r.hits, r.misses, r.unmatched, r.misses.saturating_sub(r.unmatched), r.skipped, r.total,
    );
    eprintln!("  Miss report: {}", r.report_path.display());

    assert!(r.compared > 0, "No lines compared");
    assert!(
        r.accuracy >= MIN_ACCURACY,
        "AA accuracy {:.1}% below threshold {:.0}% ({}/{}) — see {}",
        r.accuracy * 100.0,
        MIN_ACCURACY * 100.0,
        r.hits,
        r.compared,
        r.report_path.display(),
    );
}

#[test]
fn specimen_vectorizes_enough_lines() {
    ensure_index();
    ensure_specimen();

    let vector_src = test_doc("font-timeline-specimen.pdf");
    let input = test_doc("font-timeline-specimen-rasterized.pdf");
    if !input.exists() {
        assert!(
            common::rasterize_pdf(&vector_src, &input, 300, true),
            "rasterization failed",
        );
    }

    let output = common::run_unscan(&input, &[]);
    let count = common::parse_vectorized_count(&output)
        .expect("could not parse vectorized count");

    eprintln!("specimen vectorized = {}", count);
    assert!(count >= 350, "specimen vectorized {} lines, expected >= 350", count);
}
