//! Cross-renderer accuracy tests.
//!
//! The CI font index is built from ab_glyph renders (FreeType-based). These
//! tests rasterize the specimen PDF using Poppler/Cairo — a different rendering
//! engine with different hinting, stem placement, and anti-aliasing decisions.
//!
//! This is the same kind of variation seen between different printers/drivers
//! in real scanned documents: stems land on different pixel boundaries,
//! anti-aliasing kernels differ, and gray-level distributions shift.
//!
//! Prerequisites: run t55_specimen_gen first to generate base fixtures.
//!
//! Run with:
//!   cargo test --release --test t62_cross_renderer_accuracy -- --nocapture
//!
//! Requires: pdftoppm (Poppler), img2pdf, PIL/numpy, PyMuPDF (Python).

mod common;

use common::{test_doc, ensure_index};

/// Poppler renders with different hinting than the CI's FreeType backend.
/// Lower than t60's threshold to account for cross-renderer feature drift.
const MIN_ACCURACY_POPPLER_AA: f64 = 0.98;

#[test]
fn specimen_font_accuracy_poppler() {
    ensure_index();

    let vector = test_doc("font-timeline-specimen.pdf");
    let fontmap = test_doc("font-timeline-specimen-fontmap.json");

    assert!(vector.exists(),
        "Vector specimen missing — run t55_specimen_gen first: {}",
        vector.display());

    // Rasterize with Poppler — this is the cross-renderer variant, not pre-generated by t55.
    let poppler_pdf = test_doc("font-timeline-specimen-rasterized-poppler.pdf");
    assert!(
        common::rasterize_pdf_poppler(&vector, &poppler_pdf, 300, true),
        "Poppler rasterization failed (pdftoppm missing?)",
    );

    let r = common::measure_accuracy(&poppler_pdf, &vector, &fontmap, "t62-poppler-300dpi-aa");

    eprintln!(
        "Poppler AA @ 300dpi: {}/{} = {:.1}% (threshold: {:.0}%)",
        r.hits, r.compared, r.accuracy * 100.0, MIN_ACCURACY_POPPLER_AA * 100.0,
    );
    eprintln!(
        "  {} hits, {} misses ({} unmatched, {} wrong), {} skipped, {} total",
        r.hits, r.misses, r.unmatched, r.misses.saturating_sub(r.unmatched), r.skipped, r.total,
    );
    eprintln!("  Miss report: {}", r.report_path.display());

    assert!(
        r.compared > 0,
        "No lines compared — audit or char-misses.py produced no results",
    );
    assert!(
        r.accuracy >= MIN_ACCURACY_POPPLER_AA,
        "Poppler accuracy {:.1}% below threshold {:.0}% ({}/{}) — see {}",
        r.accuracy * 100.0,
        MIN_ACCURACY_POPPLER_AA * 100.0,
        r.hits,
        r.compared,
        r.report_path.display(),
    );
}
