[package]
name = "unprint-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "unprint"
path = "src/main.rs"

[dependencies]
unprint = { path = "../.." }
unprint-report = { path = "../unprint-report" }
unprint-fonts = { path = "../unprint-fonts" }
unprint-geometry = { path = "../unprint-geometry" }
clap = { workspace = true }
image = { workspace = true }
lopdf = { workspace = true }
walkdir = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
subsetter = { workspace = true }
base64 = { workspace = true }
libm = { workspace = true }
rustc-hash = { workspace = true }
rand = { workspace = true }
write-fonts = { workspace = true }
read-fonts = { workspace = true }
font-types = { workspace = true }
flate2 = { workspace = true }
memmap2 = { workspace = true }
pprof = { workspace = true, optional = true }

[features]
report = []
profile = ["pprof", "unprint/profile"]
