#!/usr/bin/env python3
"""Build a ground-truth font file map from any vector PDF.

Reads the finished PDF, extracts every embedded PostScript font name,
and reverse-resolves each to a file path via fontconfig.  The output
JSON can be fed to `unscan --include-fontmap` and `char-misses.py --fontmap`.

Usage:
    python3 tools/build-fontmap.py document.pdf              # prints to stdout
    python3 tools/build-fontmap.py document.pdf -o map.json  # writes to file

Works on any vector PDF — not limited to specimen PDFs generated by gen-specimen.py.
The only requirement is that the fonts embedded in the PDF are also installed on the
system where this script runs (so fontconfig can resolve PS name → file).
"""

import argparse
import json
import subprocess
import sys

import fitz  # PyMuPDF


def build_fontmap(pdf_path):
    """Extract font file map by introspecting a vector PDF.

    Returns dict mapping PostScript name → absolute file path.
    Built-in PDF fonts (Helvetica, Courier, etc.) with no local file are omitted.
    """
    doc = fitz.open(str(pdf_path))
    fontmap = {}

    for page_num in range(len(doc)):
        for font_entry in doc[page_num].get_fonts(full=True):
            basefont = font_entry[3]
            # Strip subset prefix (AAAAAA+FontName → FontName)
            if '+' in basefont:
                basefont = basefont.split('+', 1)[1]
            if basefont in fontmap:
                continue

            # Reverse-resolve: PS name → file path via fontconfig
            r = subprocess.run(
                ['fc-list', f':postscriptname={basefont}', '--format=%{file}\n'],
                capture_output=True, text=True
            )
            files = [l for l in r.stdout.strip().split('\n') if l]
            if files:
                # Prefer .ttf (TrueType outlines)
                ttf = [f for f in files if f.lower().endswith('.ttf')]
                fontmap[basefont] = ttf[0] if ttf else files[0]
            else:
                fontmap[basefont] = None

    doc.close()

    # Drop unresolvable builtins
    resolved = {k: v for k, v in sorted(fontmap.items()) if v is not None}
    unresolved = [k for k, v in fontmap.items() if v is None]

    return resolved, unresolved


def main():
    parser = argparse.ArgumentParser(
        description="Build a ground-truth font file map from a vector PDF."
    )
    parser.add_argument("pdf", help="Path to the vector PDF")
    parser.add_argument("-o", "--output", help="Output JSON file (default: stdout)")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Print summary to stderr")
    args = parser.parse_args()

    resolved, unresolved = build_fontmap(args.pdf)

    if args.verbose or not args.output:
        print(f"{len(resolved)} fonts resolved, {len(unresolved)} unresolved",
              file=sys.stderr)
        if unresolved:
            for name in unresolved:
                print(f"  unresolved (builtin?): {name}", file=sys.stderr)

    output = json.dumps(resolved, indent=2, sort_keys=True)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(output + '\n')
        if args.verbose:
            print(f"Wrote {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
