#!/usr/bin/env python3
"""Compute LDA projection matrix from unscan feature vectors."""

import json
import sys
import numpy as np

print("Loading features CSV...", file=sys.stderr)
# Read CSV efficiently — skip header, parse font_name as string, rest as float
import csv

font_names = []
features = []
with open("/tmp/features.csv") as f:
    reader = csv.reader(f)
    header = next(reader)
    feat_start = 3  # font_name, char, dpi, then 99 features
    n_feat = len(header) - feat_start
    print(f"  {n_feat} feature columns", file=sys.stderr)
    
    # Subsample to ~200K rows to fit in memory
    # Read all, then subsample
    count = 0
    for row in reader:
        font_names.append(row[0])
        features.append([float(x) for x in row[feat_start:]])
        count += 1
        if count % 200000 == 0:
            print(f"  loaded {count} rows...", file=sys.stderr)

print(f"  {count} total rows loaded", file=sys.stderr)

X = np.array(features, dtype=np.float32)
del features  # free memory
y = np.array(font_names)
del font_names

print(f"  X shape: {X.shape}", file=sys.stderr)

# Subsample if needed
max_rows = 200000
if len(X) > max_rows:
    print(f"  Subsampling to {max_rows} rows...", file=sys.stderr)
    rng = np.random.RandomState(42)
    idx = rng.choice(len(X), max_rows, replace=False)
    X = X[idx]
    y = y[idx]

n_classes = len(np.unique(y))
print(f"  {n_classes} unique fonts", file=sys.stderr)

# LDA
print("Fitting LDA...", file=sys.stderr)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# n_components = min(n_classes - 1, n_features) = min(~1400, 99) = 99
lda = LinearDiscriminantAnalysis(n_components=min(n_classes - 1, X.shape[1]))
lda.fit(X, y)

# The transformation matrix: scalings_ is (n_features, n_components)
proj = lda.scalings_  # shape (99, n_components)
explained = lda.explained_variance_ratio_ if hasattr(lda, 'explained_variance_ratio_') else None

print(f"  Projection matrix shape: {proj.shape}", file=sys.stderr)
if explained is not None:
    cumsum = np.cumsum(explained)
    for k in [10, 20, 30, 50, 70, 99]:
        if k <= len(cumsum):
            print(f"  Top {k} LDA dims explain {cumsum[k-1]*100:.1f}% of between-class variance", file=sys.stderr)

# Output as JSON
output = {
    "projection_matrix": proj.tolist(),
    "n_features_in": int(proj.shape[0]),
    "n_components_out": int(proj.shape[1]),
    "explained_variance_ratio": explained.tolist() if explained is not None else None,
}
with open("/tmp/lda_matrix.json", "w") as f:
    json.dump(output, f)

# Also output as a Rust const for embedding
print(f"\nProjection matrix saved to /tmp/lda_matrix.json", file=sys.stderr)

# Output a compact Rust file
with open("/tmp/lda_projection.rs", "w") as f:
    n_out = proj.shape[1]
    f.write(f"// LDA projection matrix: {proj.shape[0]} features → {n_out} components\n")
    f.write(f"// Generated by tools/compute_lda.py\n\n")
    f.write(f"pub const LDA_N_COMPONENTS: usize = {n_out};\n\n")
    f.write(f"pub const LDA_PROJECTION: [[f32; {n_out}]; {proj.shape[0]}] = [\n")
    for row in proj:
        vals = ", ".join(f"{v:.6}" for v in row)
        f.write(f"    [{vals}],\n")
    f.write("];\n")

print(f"Rust const saved to /tmp/lda_projection.rs", file=sys.stderr)
print(f"Done.", file=sys.stderr)
