//! Per-character font index and matcher.
//!
//! Instead of assembling a magic word, we build a feature index for **every
//! common character** rendered in each candidate font.  At match time we crop
//! individual characters from the longest OCR words in the scan and compare
//! their feature vectors against the index.
//!
//! ## Indexed characters
//! Printable ASCII (a-z, A-Z, 0-9, common punctuation) plus typographic
//! specials: em dash, en dash, smart quotes, ellipsis.
//!
//! ## Feature vector per character
//! - Column ink density profile (32 bins)
//! - Aspect ratio (ink width / ink height)
//! - Ink density (total ink / bbox area)
//! - Vertical centre of mass (0.0 = top, 1.0 = bottom)
//! - Horizontal balance (left-half ink / total ink)
//!
//! ## Extraction strategy
//! Pick the longest words in the line (≥3 chars), segment each into
//! per-character crops via column-ink valley detection, normalise to
//! `NORM_H`, return `(char, image)` pairs.
//!
//! ## Lookup
//! Uses a per-character k-d tree for O(D·log N) spatial lookup with
//! tolerance-band radius queries instead of brute-force cosine scan.

use ab_glyph::{Font, FontRef, PxScale, ScaleFont, point};
use image::{GrayImage, Luma};
use std::collections::HashMap;
use std::io;
use std::path::Path;

use crate::verify::WordPlacement;
use crate::segment::{segment_characters, segment_characters_diag};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Per-dimension Fisher weights from learn_weights analysis.
/// Scale-adjusted: sqrt(fisher_ratio) / std_total, normalized to sum=1.
/// Generated by: cargo run --release --bin learn_weights
const FISHER_WEIGHTS: [f32; FEAT_LEN] = [
    // Col profile (32)
    0.003953, 0.004824, 0.005614, 0.005755, 0.005833, 0.006375, 0.007151, 0.007835,
    0.008234, 0.008618, 0.008887, 0.009053, 0.009226, 0.009574, 0.009938, 0.010845,
    0.010942, 0.010045, 0.009682, 0.009602, 0.009413, 0.009146, 0.008888, 0.008598,
    0.008158, 0.007642, 0.007122, 0.006609, 0.006260, 0.005820, 0.005091, 0.004272,
    // Scalar v1 (7)
    0.014034, 0.014155, 0.076659, 0.017971, 0.004810, 0.000499, 0.000000,
    // Scalar v2 (18)
    0.019123, 0.007358, 0.008091, 0.002813, 0.008683, 0.005711, 0.008230, 0.004566,
    0.008775, 0.012152, 0.015823, 0.021353, 0.022005, 0.023333, 0.021497, 0.020949,
    0.021674, 0.017132,
    // Row profile (32)
    0.002173, 0.003205, 0.004666, 0.005026, 0.007098, 0.009250, 0.010297, 0.010096,
    0.010372, 0.009552, 0.010717, 0.009948, 0.010392, 0.010256, 0.009733, 0.010295,
    0.010157, 0.009540, 0.009676, 0.010025, 0.009587, 0.010488, 0.009938, 0.010414,
    0.009994, 0.010259, 0.009381, 0.007008, 0.005009, 0.004858, 0.003325, 0.002274,
    // Scalar v3 (10)
    0.010598, 0.013312, 0.018844, 0.002806, 0.008651, 0.006412, 0.012406, 0.011526,
    0.010916, 0.013117,
];

/// Normalised character height for all feature computation.
const NORM_H: u32 = 48;

/// Number of bins in the column ink density profile.
const PROFILE_BINS: usize = 32;

/// Number of bins in the row ink density profile (horizontal).
const ROW_PROFILE_BINS: usize = 32;

/// Number of horizontal crossing scan lines.
const CROSSING_BINS: usize = 8;

/// Number of terminal angle bins (up/right/down/left).
const TERMINAL_ANGLE_BINS: usize = 4;

/// Number of original scalar features (aspect..xh_cap_ratio).
const SCALAR_V1: usize = 7;

/// Number of new discriminative scalar features.
const SCALAR_V2: usize = 4 + TERMINAL_ANGLE_BINS + 2 + CROSSING_BINS;
// counter_area_ratio(1) + counter_centroid(2) + counter_aspect(1) = 4
// terminal_count is folded into terminal_angles normalization
// terminal_angles(4) + ink_perimeter(1) + compactness(1) = 6
// h_crossings(8)

/// Number of v3 feature dimensions.
const SCALAR_V3: usize = 1 + 1 + 1 + 2 + 1 + 4;
// hole_count(1) + h_symmetry(1) + v_symmetry(1) + skeleton(branch_pts, end_pts = 2) + corner_count(1) + quadrant_density(4)

/// Feature vector length: col_profile + row_profile + original scalars + v2 + v3.
pub const FEAT_LEN: usize = PROFILE_BINS + ROW_PROFILE_BINS + SCALAR_V1 + SCALAR_V2 + SCALAR_V3;

/// Minimum word length (characters) for extraction.
const MIN_WORD_LEN: usize = 3;

// ---------------------------------------------------------------------------
// Indexed character set
// ---------------------------------------------------------------------------

/// Returns the full set of characters we index.
pub fn indexed_chars() -> &'static [char] {
    static CHARS: std::sync::LazyLock<Vec<char>> = std::sync::LazyLock::new(|| {
        let mut v: Vec<char> = Vec::with_capacity(128);
        for c in 'a'..='z' { v.push(c); }
        for c in 'A'..='Z' { v.push(c); }
        for c in '0'..='9' { v.push(c); }
        for c in &[
            '!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',',
            '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\',
            ']', '^', '_', '`', '{', '|', '}', '~',
        ] {
            v.push(*c);
        }
        v.push('\u{2014}'); // em dash
        v.push('\u{2013}'); // en dash
        v.push('\u{2018}'); // left single quote
        v.push('\u{2019}'); // right single quote
        v.push('\u{201C}'); // left double quote
        v.push('\u{201D}'); // right double quote
        v.push('\u{2026}'); // ellipsis
        v
    });
    &CHARS
}

/// Quick membership test.
fn is_indexed(c: char) -> bool {
    indexed_chars().contains(&c)
}

// ---------------------------------------------------------------------------
// Feature vector
// ---------------------------------------------------------------------------

/// Compact feature vector for one character rendering.
#[derive(Debug, Clone)]
pub struct CharFeatures {
    /// 32-bin column ink density profile (each 0.0–1.0).
    pub profile: [f32; PROFILE_BINS],
    /// Ink width / ink height.
    pub aspect: f32,
    /// Total ink pixels / bounding-box area.
    pub ink_density: f32,
    /// Vertical centre of mass (0.0 = top, 1.0 = bottom).
    pub v_center: f32,
    /// Left-half ink / total ink.
    pub h_balance: f32,
    /// Serif confidence score (0.0 = sans-serif, 1.0 = definite serif).
    pub serif_score: f32,
    /// Stroke contrast: ratio of thickest to thinnest strokes.
    pub stroke_contrast: f32,
    /// x-height to cap-height ratio (per-font metric).
    pub xh_cap_ratio: f32,

    // ── v2 discriminative features ──────────────────────────────────
    /// Counter (enclosed whitespace) area / total bbox area. 0 if no counter.
    pub counter_area_ratio: f32,
    /// Counter centroid X, normalised to [0,1] within ink bbox.
    pub counter_centroid_x: f32,
    /// Counter centroid Y, normalised to [0,1] within ink bbox.
    pub counter_centroid_y: f32,
    /// Counter aspect ratio (width/height of counter bbox). 0 if no counter.
    pub counter_aspect: f32,
    /// Terminal angle histogram: 4 bins (up/right/down/left), normalised.
    pub terminal_angles: [f32; TERMINAL_ANGLE_BINS],
    /// Ink perimeter / sqrt(ink_area). Normalised boundary complexity.
    pub ink_perimeter: f32,
    /// Compactness: 4π × area / perimeter². Circle=1.0, complex<1.0.
    pub compactness: f32,
    /// Horizontal crossings at 8 evenly-spaced scan lines. Each value is
    /// the number of ink↔white transitions, normalised by dividing by 20.
    pub h_crossings: [f32; CROSSING_BINS],

    // ── v3 discriminative features ──────────────────────────────────
    /// Row ink density profile (32 bins, horizontal analog of column profile).
    pub row_profile: [f32; ROW_PROFILE_BINS],
    /// Number of enclosed white regions (holes), normalised by dividing by 4.
    pub hole_count: f32,
    /// Horizontal mirror symmetry score (0.0 = asymmetric, 1.0 = perfect mirror).
    pub h_symmetry: f32,
    /// Vertical mirror symmetry score (0.0 = asymmetric, 1.0 = perfect mirror).
    pub v_symmetry: f32,
    /// Skeleton branch points (3+ neighbors), normalised by dividing by 10.
    pub skeleton_branch_pts: f32,
    /// Skeleton endpoints (1 neighbor), normalised by dividing by 10.
    pub skeleton_end_pts: f32,
    /// Corner count (sharp direction changes on ink boundary), normalised by dividing by 20.
    pub corner_count: f32,
    /// Ink density in each quadrant (TL, TR, BL, BR), each 0.0–1.0.
    pub quadrant_density: [f32; 4],
}

impl CharFeatures {
    /// Raw feature vector for serialisation (no normalisation).
    pub fn as_slice(&self) -> [f32; FEAT_LEN] {
        let mut v = [0.0f32; FEAT_LEN];
        let mut i = 0;
        // Column profile (32)
        v[i..i + PROFILE_BINS].copy_from_slice(&self.profile);
        i += PROFILE_BINS;
        // Original scalars (7)
        v[i] = self.aspect;           i += 1;
        v[i] = self.ink_density;      i += 1;
        v[i] = self.v_center;         i += 1;
        v[i] = self.h_balance;        i += 1;
        v[i] = self.serif_score;      i += 1;
        v[i] = self.stroke_contrast;  i += 1;
        v[i] = self.xh_cap_ratio;     i += 1;
        // v2: counter features (4)
        v[i] = self.counter_area_ratio;   i += 1;
        v[i] = self.counter_centroid_x;   i += 1;
        v[i] = self.counter_centroid_y;   i += 1;
        v[i] = self.counter_aspect;       i += 1;
        // v2: terminal angles (4)
        v[i..i + TERMINAL_ANGLE_BINS].copy_from_slice(&self.terminal_angles);
        i += TERMINAL_ANGLE_BINS;
        // v2: boundary features (2)
        v[i] = self.ink_perimeter;    i += 1;
        v[i] = self.compactness;      i += 1;
        // v2: horizontal crossings (8)
        v[i..i + CROSSING_BINS].copy_from_slice(&self.h_crossings);
        i += CROSSING_BINS;
        // v3: row profile (32)
        v[i..i + ROW_PROFILE_BINS].copy_from_slice(&self.row_profile);
        i += ROW_PROFILE_BINS;
        // v3: scalars (10)
        v[i] = self.hole_count;           i += 1;
        v[i] = self.h_symmetry;           i += 1;
        v[i] = self.v_symmetry;           i += 1;
        v[i] = self.skeleton_branch_pts;  i += 1;
        v[i] = self.skeleton_end_pts;     i += 1;
        v[i] = self.corner_count;         i += 1;
        v[i..i + 4].copy_from_slice(&self.quadrant_density);
        // i += 4;  // last group
        debug_assert_eq!(i + 4, FEAT_LEN);
        v
    }

    /// Weighted feature vector for matching.
    /// Per-dimension Fisher-weighted feature vector.
    pub fn weighted(&self) -> [f32; FEAT_LEN] {
        let raw = self.as_slice();
        let mut v = [0.0f32; FEAT_LEN];
        for i in 0..FEAT_LEN {
            v[i] = raw[i] * FISHER_WEIGHTS[i];
        }
        v
    }
}

// ---------------------------------------------------------------------------
// Brute-force nearest-neighbor search
// ---------------------------------------------------------------------------
// At 59 dimensions the KD-tree degrades to near-linear scan anyway (the
// single-axis pruning test checks 1/59th of total distance — far branch is
// almost always explored). A flat vector with linear scan is simpler, faster
// (cache-friendly + LLVM auto-vectorizes the distance loop), and trivially
// correct.

/// Find the nearest neighbor, then return ALL points within `factor`× that
/// distance. Returns `(font_id, squared_distance)` pairs sorted by distance.
fn nearest_within_factor_brute(
    points: &[(usize, [f32; FEAT_LEN])],
    query: &[f32; FEAT_LEN],
    factor: f32,
) -> Vec<(usize, f32)> {
    if points.is_empty() {
        return Vec::new();
    }
    // Single pass: find min squared distance
    let mut best_dist_sq = f32::MAX;
    for (_, coords) in points {
        let d = squared_distance(coords, query);
        if d < best_dist_sq {
            best_dist_sq = d;
        }
    }
    let cutoff = factor * factor * best_dist_sq.max(1e-12);
    // Second pass: collect everything within cutoff
    let mut results: Vec<(usize, f32)> = points.iter()
        .filter_map(|(id, coords)| {
            let d = squared_distance(coords, query);
            if d <= cutoff { Some((*id, d)) } else { None }
        })
        .collect();
    results.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
    results
}

/// Squared Euclidean distance between two feature vectors.
fn squared_distance(a: &[f32; FEAT_LEN], b: &[f32; FEAT_LEN]) -> f32 {
    let mut sum = 0.0f32;
    for i in 0..FEAT_LEN {
        let d = a[i] - b[i];
        sum += d * d;
    }
    sum
}

// ---------------------------------------------------------------------------
// New typographic feature extraction
// ---------------------------------------------------------------------------

/// Detect whether a glyph image shows serifs.
fn detect_serif(img: &GrayImage) -> f32 {
    let (w, h) = img.dimensions();
    if w < 3 || h < 8 {
        return 0.0;
    }

    let threshold = 200u8;
    let mut row_ink = vec![0u32; h as usize];
    let mut min_y = h;
    let mut max_y = 0u32;

    for y in 0..h {
        let mut count = 0u32;
        for x in 0..w {
            if img.get_pixel(x, y).0[0] < threshold {
                count += 1;
            }
        }
        row_ink[y as usize] = count;
        if count > 0 {
            if y < min_y { min_y = y; }
            if y > max_y { max_y = y; }
        }
    }

    let ink_h = max_y.saturating_sub(min_y) + 1;
    if ink_h < 8 {
        return 0.0;
    }

    let terminal_rows = (ink_h / 8).max(2).min(4);

    let top_ink: f32 = (min_y..min_y + terminal_rows)
        .map(|y| row_ink[y as usize] as f32)
        .sum::<f32>() / terminal_rows as f32;
    let bot_ink: f32 = ((max_y + 1 - terminal_rows)..=max_y)
        .map(|y| row_ink[y as usize] as f32)
        .sum::<f32>() / terminal_rows as f32;

    let mid_start = min_y + ink_h / 3;
    let mid_end = min_y + 2 * ink_h / 3;
    let mid_rows = (mid_end - mid_start).max(1);
    let mid_ink: f32 = (mid_start..mid_end)
        .map(|y| row_ink[y as usize] as f32)
        .sum::<f32>() / mid_rows as f32;

    if mid_ink < 1.0 {
        return 0.0;
    }

    let top_ratio = top_ink / mid_ink;
    let bot_ratio = bot_ink / mid_ink;
    let avg_ratio = (top_ratio + bot_ratio) / 2.0;

    ((avg_ratio - 1.0)).clamp(0.0, 1.0)
}

/// Compute a per-font serif confidence score.
pub fn compute_font_serif_score<F: Font>(font: &F) -> f32 {
    let diag_chars = ['I', 'l'];
    let mut scores = Vec::new();

    for &c in &diag_chars {
        if let Some(img) = render_char_normalised(font, c) {
            let s = detect_serif(&img);
            scores.push(s);
        }
    }

    if scores.is_empty() {
        return 0.0;
    }

    let sum: f32 = scores.iter().sum();
    (sum / scores.len() as f32).clamp(0.0, 1.0)
}

/// Measure stroke contrast (thick-to-thin ratio) from a glyph image.
fn measure_stroke_contrast(img: &GrayImage) -> f32 {
    let (w, h) = img.dimensions();
    if w < 4 || h < 4 {
        return 1.0;
    }

    let threshold = 200u8;
    let mut all_runs: Vec<u32> = Vec::new();

    for y in 0..h {
        let mut run = 0u32;
        for x in 0..w {
            if img.get_pixel(x, y).0[0] < threshold {
                run += 1;
            } else {
                if run >= 2 { all_runs.push(run); }
                run = 0;
            }
        }
        if run >= 2 { all_runs.push(run); }
    }

    for x in 0..w {
        let mut run = 0u32;
        for y in 0..h {
            if img.get_pixel(x, y).0[0] < threshold {
                run += 1;
            } else {
                if run >= 2 { all_runs.push(run); }
                run = 0;
            }
        }
        if run >= 2 { all_runs.push(run); }
    }

    if all_runs.len() < 4 {
        return 1.0;
    }

    all_runs.sort_unstable();
    let p10 = all_runs[all_runs.len() / 10].max(1);
    let p90 = all_runs[all_runs.len() * 9 / 10].max(1);

    p90 as f32 / p10 as f32
}

/// Compute x-height / cap-height ratio for a font.
pub fn compute_xh_cap_ratio<F: Font>(font: &F) -> f32 {
    let scale = PxScale::from(200.0);

    let ink_height_at_scale = |c: char| -> Option<f32> {
        let gid = font.glyph_id(c);
        if gid.0 == 0 { return None; }
        let sf = font.as_scaled(scale);
        let glyph = gid.with_scale_and_position(scale, point(0.0, sf.ascent()));
        let outlined = font.outline_glyph(glyph)?;
        let b = outlined.px_bounds();
        let ih = b.max.y - b.min.y;
        if ih > 0.5 { Some(ih) } else { None }
    };

    match (ink_height_at_scale('x'), ink_height_at_scale('H')) {
        (Some(xh), Some(ch)) if ch > 0.0 => (xh / ch).clamp(0.0, 1.0),
        _ => 0.65,
    }
}

/// Character discriminativeness weight for scoring.
fn char_weight(c: char) -> f32 {
    match c {
        'g' | 'a' | 'e' | 'R' | 'Q' | 'G' | 'S' | 'f' | 't' | 'y' | '&' | '@' => 1.5,
        'I' | 'l' | '1' | '|' | '!' | '.' | ',' | ':' | ';' | '-' => 0.5,
        'b' | 'd' | 'p' | 'q' | 'n' | 'u' | 'o' | 'c' | 'O' | 'C' | 'D' => 0.8,
        'k' | 'w' | 'x' | 'z' | 'A' | 'B' | 'E' | 'F' | 'K' | 'M' | 'N' | 'W' => 1.2,
        _ => 1.0,
    }
}

// ---------------------------------------------------------------------------
// Feature computation
// ---------------------------------------------------------------------------

/// Compute features from a normalised grayscale glyph image.
pub fn compute_features(img: &GrayImage) -> Option<CharFeatures> {
    let (w, h) = img.dimensions();
    if w == 0 || h == 0 {
        return None;
    }

    let threshold = 200u8;
    let mut min_x = w;
    let mut max_x = 0u32;
    let mut min_y = h;
    let mut max_y = 0u32;
    let mut total_ink = 0u64;
    let mut ink_pixels = 0u64;
    let mut wy_sum = 0.0f64;

    for y in 0..h {
        for x in 0..w {
            let px = img.get_pixel(x, y).0[0];
            if px < threshold {
                let ink_val = (255 - px) as u64;
                total_ink += ink_val;
                ink_pixels += 1;
                wy_sum += y as f64 * ink_val as f64;
                if x < min_x { min_x = x; }
                if x > max_x { max_x = x; }
                if y < min_y { min_y = y; }
                if y > max_y { max_y = y; }
            }
        }
    }

    if ink_pixels == 0 || total_ink == 0 {
        return None;
    }

    let ink_w = (max_x - min_x + 1) as f32;
    let ink_h = (max_y - min_y + 1) as f32;
    let aspect = ink_w / ink_h.max(1.0);
    let bbox_area = ink_w * ink_h;
    let ink_density = ink_pixels as f32 / bbox_area.max(1.0);
    let v_center = (wy_sum / total_ink as f64) as f32 / h as f32;

    let ink_mid_x = (min_x + max_x) / 2;
    let mut left_ink = 0u64;
    for y in 0..h {
        for x in 0..w {
            let px = img.get_pixel(x, y).0[0];
            if px < threshold {
                let ink_val = (255 - px) as u64;
                if x <= ink_mid_x {
                    left_ink += ink_val;
                }
            }
        }
    }
    let h_balance = left_ink as f32 / total_ink as f32;

    let mut col_ink = vec![0.0f32; ink_w as usize];
    for x in min_x..=max_x {
        let mut col_sum = 0.0f32;
        for y in min_y..=max_y {
            let px = img.get_pixel(x, y).0[0];
            if px < threshold {
                col_sum += (255 - px) as f32;
            }
        }
        col_ink[(x - min_x) as usize] = col_sum;
    }
    let col_max = col_ink.iter().cloned().fold(0.0f32, f32::max);
    if col_max > 0.0 {
        for v in &mut col_ink {
            *v /= col_max;
        }
    }
    let profile = resample(&col_ink, PROFILE_BINS);

    // ── Row ink density profile (horizontal analog of column profile) ──
    let mut row_ink = vec![0.0f32; ink_h as usize];
    for y in min_y..=max_y {
        let mut row_sum = 0.0f32;
        for x in min_x..=max_x {
            let px = img.get_pixel(x, y).0[0];
            if px < threshold {
                row_sum += (255 - px) as f32;
            }
        }
        row_ink[(y - min_y) as usize] = row_sum;
    }
    let row_max = row_ink.iter().cloned().fold(0.0f32, f32::max);
    if row_max > 0.0 {
        for v in &mut row_ink {
            *v /= row_max;
        }
    }
    let row_profile = resample(&row_ink, ROW_PROFILE_BINS);

    let serif_score = detect_serif(img);
    let stroke_contrast_val = measure_stroke_contrast(img);

    // ── v2 features ────────────────────────────────────────────────

    // Build a binary ink mask within ink bbox for reuse
    let ink_w_u = (max_x - min_x + 1) as usize;
    let ink_h_u = (max_y - min_y + 1) as usize;
    let mut ink_mask = vec![false; ink_w_u * ink_h_u];
    for y in min_y..=max_y {
        for x in min_x..=max_x {
            if img.get_pixel(x, y).0[0] < threshold {
                ink_mask[(y - min_y) as usize * ink_w_u + (x - min_x) as usize] = true;
            }
        }
    }

    // Counter shape analysis: flood-fill from edges, remaining white = counter
    let (counter_area_ratio, counter_centroid_x, counter_centroid_y, counter_aspect) =
        compute_counter_features(&ink_mask, ink_w_u, ink_h_u);

    // Terminal / endpoint analysis
    let terminal_angles = compute_terminal_angles(&ink_mask, ink_w_u, ink_h_u);

    // Boundary complexity
    let (ink_perimeter, compactness) =
        compute_boundary_features(&ink_mask, ink_w_u, ink_h_u, ink_pixels as f32);

    // Horizontal crossings
    let h_crossings = compute_h_crossings(&ink_mask, ink_w_u, ink_h_u);

    // ── v3 features ────────────────────────────────────────────────

    // Hole count: enclosed white regions from flood-fill
    let hole_count = compute_hole_count(&ink_mask, ink_w_u, ink_h_u);

    // H/V symmetry scores
    let (h_symmetry, v_symmetry) = compute_symmetry(&ink_mask, ink_w_u, ink_h_u);

    // Skeleton topology: branch points and endpoints from morphological thinning
    let (skeleton_branch_pts, skeleton_end_pts) = compute_skeleton_features(&ink_mask, ink_w_u, ink_h_u);

    // Corner count: sharp direction changes on ink boundary
    let corner_count = compute_corner_count(&ink_mask, ink_w_u, ink_h_u);

    // Quadrant density: ink density in each quadrant (TL, TR, BL, BR)
    let quadrant_density = compute_quadrant_density(&ink_mask, ink_w_u, ink_h_u);

    Some(CharFeatures {
        profile,
        row_profile,
        aspect,
        ink_density,
        v_center,
        h_balance,
        serif_score,
        stroke_contrast: stroke_contrast_val,
        xh_cap_ratio: 0.0,
        counter_area_ratio,
        counter_centroid_x,
        counter_centroid_y,
        counter_aspect,
        terminal_angles,
        ink_perimeter,
        compactness,
        h_crossings,
        hole_count,
        h_symmetry,
        v_symmetry,
        skeleton_branch_pts,
        skeleton_end_pts,
        corner_count,
        quadrant_density,
    })
}

// ---------------------------------------------------------------------------
// v2 discriminative feature helpers
// ---------------------------------------------------------------------------

/// Counter shape analysis via edge flood-fill.
///
/// Flood-fills white pixels from edges of the ink bounding box. Any white pixels
/// NOT reached are enclosed counters (e.g. the hole in 'o', 'a', 'e').
fn compute_counter_features(ink_mask: &[bool], w: usize, h: usize) -> (f32, f32, f32, f32) {
    if w == 0 || h == 0 {
        return (0.0, 0.0, 0.0, 0.0);
    }

    let total = w * h;
    let mut reachable = vec![false; total];
    let mut queue = std::collections::VecDeque::new();

    // Seed from all edge pixels that are NOT ink
    for x in 0..w {
        if !ink_mask[x] && !reachable[x] {
            reachable[x] = true;
            queue.push_back((x, 0usize));
        }
        let idx = (h - 1) * w + x;
        if !ink_mask[idx] && !reachable[idx] {
            reachable[idx] = true;
            queue.push_back((x, h - 1));
        }
    }
    for y in 0..h {
        let idx = y * w;
        if !ink_mask[idx] && !reachable[idx] {
            reachable[idx] = true;
            queue.push_back((0, y));
        }
        let idx = y * w + (w - 1);
        if !ink_mask[idx] && !reachable[idx] {
            reachable[idx] = true;
            queue.push_back((w - 1, y));
        }
    }

    // BFS flood fill
    while let Some((x, y)) = queue.pop_front() {
        let neighbors: [(i32, i32); 4] = [(-1, 0), (1, 0), (0, -1), (0, 1)];
        for (dx, dy) in &neighbors {
            let nx = x as i32 + dx;
            let ny = y as i32 + dy;
            if nx < 0 || ny < 0 || nx >= w as i32 || ny >= h as i32 {
                continue;
            }
            let nidx = ny as usize * w + nx as usize;
            if !ink_mask[nidx] && !reachable[nidx] {
                reachable[nidx] = true;
                queue.push_back((nx as usize, ny as usize));
            }
        }
    }

    // Counter pixels: white (not ink) AND not reachable from edges
    let mut counter_area = 0u32;
    let mut cx_sum = 0.0f64;
    let mut cy_sum = 0.0f64;
    let mut counter_min_x = w;
    let mut counter_max_x = 0usize;
    let mut counter_min_y = h;
    let mut counter_max_y = 0usize;

    for y in 0..h {
        for x in 0..w {
            let idx = y * w + x;
            if !ink_mask[idx] && !reachable[idx] {
                counter_area += 1;
                cx_sum += x as f64;
                cy_sum += y as f64;
                if x < counter_min_x { counter_min_x = x; }
                if x > counter_max_x { counter_max_x = x; }
                if y < counter_min_y { counter_min_y = y; }
                if y > counter_max_y { counter_max_y = y; }
            }
        }
    }

    if counter_area == 0 {
        return (0.0, 0.0, 0.0, 0.0);
    }

    let area_ratio = counter_area as f32 / total as f32;
    let centroid_x = (cx_sum / counter_area as f64) as f32 / w.max(1) as f32;
    let centroid_y = (cy_sum / counter_area as f64) as f32 / h.max(1) as f32;
    let cw = (counter_max_x - counter_min_x + 1) as f32;
    let ch = (counter_max_y - counter_min_y + 1) as f32;
    let c_aspect = cw / ch.max(1.0);

    (area_ratio, centroid_x, centroid_y, c_aspect)
}

/// Terminal / endpoint analysis.
///
/// A terminal pixel has exactly 1 ink neighbor in 8-connected. We classify
/// the direction based on where the single neighbor is relative to the terminal.
/// Returns a 4-bin normalised histogram: [up, right, down, left].
fn compute_terminal_angles(ink_mask: &[bool], w: usize, h: usize) -> [f32; TERMINAL_ANGLE_BINS] {
    let mut bins = [0.0f32; TERMINAL_ANGLE_BINS]; // up, right, down, left
    if w < 3 || h < 3 {
        return bins;
    }

    let deltas: [(i32, i32); 8] = [
        (-1, -1), (0, -1), (1, -1),
        (-1,  0),          (1,  0),
        (-1,  1), (0,  1), (1,  1),
    ];

    let mut total_terminals = 0u32;

    for y in 0..h {
        for x in 0..w {
            let idx = y * w + x;
            if !ink_mask[idx] { continue; }

            // Count ink neighbors and find the single neighbor if count==1
            let mut neighbor_count = 0u32;
            let mut nb_dx = 0i32;
            let mut nb_dy = 0i32;

            for &(dx, dy) in &deltas {
                let nx = x as i32 + dx;
                let ny = y as i32 + dy;
                if nx >= 0 && ny >= 0 && (nx as usize) < w && (ny as usize) < h {
                    if ink_mask[ny as usize * w + nx as usize] {
                        neighbor_count += 1;
                        nb_dx = dx;
                        nb_dy = dy;
                    }
                }
            }

            if neighbor_count == 1 {
                total_terminals += 1;
                // The terminal points AWAY from its single neighbor
                // If neighbor is below (dy=1), terminal points up → bin 0
                // If neighbor is left (dx=-1), terminal points right → bin 1
                // If neighbor is above (dy=-1), terminal points down → bin 2
                // If neighbor is right (dx=1), terminal points left → bin 3
                let angle = (-nb_dy as f64).atan2(-nb_dx as f64); // direction away
                let deg = angle.to_degrees();
                // -180..180 → bin: up=[-135,-45), right=[-45,45), down=[45,135), left=else
                let bin = if deg >= -135.0 && deg < -45.0 {
                    0 // up
                } else if deg >= -45.0 && deg < 45.0 {
                    1 // right
                } else if deg >= 45.0 && deg < 135.0 {
                    2 // down
                } else {
                    3 // left
                };
                bins[bin] += 1.0;
            }
        }
    }

    // Normalise by total terminals (so histogram sums to 1.0)
    if total_terminals > 0 {
        for b in &mut bins {
            *b /= total_terminals as f32;
        }
    }

    bins
}

/// Boundary complexity features.
///
/// Returns (normalised_perimeter, compactness).
/// - normalised_perimeter = boundary_pixel_count / sqrt(ink_area)
///   Dividing by sqrt(area) makes it scale-independent.
/// - compactness = 4π × area / perimeter² (1.0 = circle).
fn compute_boundary_features(ink_mask: &[bool], w: usize, h: usize, ink_count: f32) -> (f32, f32) {
    if w == 0 || h == 0 || ink_count < 1.0 {
        return (0.0, 0.0);
    }

    let mut boundary_count = 0u32;

    for y in 0..h {
        for x in 0..w {
            let idx = y * w + x;
            if !ink_mask[idx] { continue; }

            // Ink pixel borders white if any 4-connected neighbor is white or out-of-bounds
            let is_boundary = (x == 0 || !ink_mask[idx - 1])
                || (x + 1 >= w || !ink_mask[idx + 1])
                || (y == 0 || !ink_mask[idx - w])
                || (y + 1 >= h || !ink_mask[idx + w]);

            if is_boundary {
                boundary_count += 1;
            }
        }
    }

    let perim = boundary_count as f32;
    let norm_perimeter = perim / ink_count.sqrt();
    let compactness = if perim > 0.0 {
        (4.0 * std::f32::consts::PI * ink_count) / (perim * perim)
    } else {
        0.0
    };

    // Cap normalised perimeter to a reasonable range for feature vector
    let norm_perimeter_capped = (norm_perimeter / 10.0).min(1.0);

    (norm_perimeter_capped, compactness)
}

/// Horizontal crossings at 8 evenly-spaced scan lines.
///
/// For each scan line, counts the number of ink→white or white→ink transitions.
/// Normalised by dividing by 20 (a reasonable cap for complex chars).
fn compute_h_crossings(ink_mask: &[bool], w: usize, h: usize) -> [f32; CROSSING_BINS] {
    let mut crossings = [0.0f32; CROSSING_BINS];
    if w == 0 || h == 0 {
        return crossings;
    }

    for bin in 0..CROSSING_BINS {
        // Evenly spaced: first at 1/(N+1), last at N/(N+1) of height
        let y = ((bin + 1) as f32 * h as f32 / (CROSSING_BINS + 1) as f32) as usize;
        let y = y.min(h - 1);

        let mut transitions = 0u32;
        let mut prev_ink = false;
        for x in 0..w {
            let is_ink = ink_mask[y * w + x];
            if is_ink != prev_ink && x > 0 {
                transitions += 1;
            }
            prev_ink = is_ink;
        }
        // Normalise (most chars have ≤10 transitions; 20 is generous cap)
        crossings[bin] = (transitions as f32 / 20.0).min(1.0);
    }

    crossings
}

// ---------------------------------------------------------------------------
// v3 discriminative feature helpers
// ---------------------------------------------------------------------------

/// Count enclosed white regions (holes) using flood-fill from edges.
/// Returns normalised count: raw_count / 4.0 (most chars have 0–3 holes).
fn compute_hole_count(ink_mask: &[bool], w: usize, h: usize) -> f32 {
    if w == 0 || h == 0 {
        return 0.0;
    }
    let total = w * h;
    let mut reachable = vec![false; total];
    let mut queue = std::collections::VecDeque::new();

    // Seed from edges
    for x in 0..w {
        if !ink_mask[x] && !reachable[x] {
            reachable[x] = true;
            queue.push_back((x, 0usize));
        }
        let idx = (h - 1) * w + x;
        if !ink_mask[idx] && !reachable[idx] {
            reachable[idx] = true;
            queue.push_back((x, h - 1));
        }
    }
    for y in 0..h {
        let idx = y * w;
        if !ink_mask[idx] && !reachable[idx] {
            reachable[idx] = true;
            queue.push_back((0, y));
        }
        let idx = y * w + (w - 1);
        if !ink_mask[idx] && !reachable[idx] {
            reachable[idx] = true;
            queue.push_back((w - 1, y));
        }
    }
    while let Some((x, y)) = queue.pop_front() {
        for (dx, dy) in &[(-1i32, 0i32), (1, 0), (0, -1), (0, 1)] {
            let nx = x as i32 + dx;
            let ny = y as i32 + dy;
            if nx >= 0 && ny >= 0 && (nx as usize) < w && (ny as usize) < h {
                let nidx = ny as usize * w + nx as usize;
                if !ink_mask[nidx] && !reachable[nidx] {
                    reachable[nidx] = true;
                    queue.push_back((nx as usize, ny as usize));
                }
            }
        }
    }

    // Count distinct enclosed white regions via another flood-fill
    let mut visited = vec![false; total];
    let mut hole_count = 0u32;
    for y in 0..h {
        for x in 0..w {
            let idx = y * w + x;
            if !ink_mask[idx] && !reachable[idx] && !visited[idx] {
                // New hole — flood-fill to mark it
                hole_count += 1;
                let mut q2 = std::collections::VecDeque::new();
                visited[idx] = true;
                q2.push_back((x, y));
                while let Some((cx, cy)) = q2.pop_front() {
                    for (dx, dy) in &[(-1i32, 0i32), (1, 0), (0, -1), (0, 1)] {
                        let nx = cx as i32 + dx;
                        let ny = cy as i32 + dy;
                        if nx >= 0 && ny >= 0 && (nx as usize) < w && (ny as usize) < h {
                            let nidx = ny as usize * w + nx as usize;
                            if !ink_mask[nidx] && !reachable[nidx] && !visited[nidx] {
                                visited[nidx] = true;
                                q2.push_back((nx as usize, ny as usize));
                            }
                        }
                    }
                }
            }
        }
    }

    (hole_count as f32 / 4.0).min(1.0)
}

/// Horizontal and vertical symmetry scores.
/// Measures how similar the ink mask is to its mirror image.
fn compute_symmetry(ink_mask: &[bool], w: usize, h: usize) -> (f32, f32) {
    if w < 2 || h < 2 {
        return (0.0, 0.0);
    }

    // Horizontal symmetry: compare left-right mirror
    let mut h_match = 0u32;
    let mut h_total = 0u32;
    for y in 0..h {
        for x in 0..w / 2 {
            let mirror_x = w - 1 - x;
            let left = ink_mask[y * w + x];
            let right = ink_mask[y * w + mirror_x];
            h_total += 1;
            if left == right {
                h_match += 1;
            }
        }
    }

    // Vertical symmetry: compare top-bottom mirror
    let mut v_match = 0u32;
    let mut v_total = 0u32;
    for y in 0..h / 2 {
        let mirror_y = h - 1 - y;
        for x in 0..w {
            let top = ink_mask[y * w + x];
            let bottom = ink_mask[mirror_y * w + x];
            v_total += 1;
            if top == bottom {
                v_match += 1;
            }
        }
    }

    let h_sym = if h_total > 0 { h_match as f32 / h_total as f32 } else { 0.0 };
    let v_sym = if v_total > 0 { v_match as f32 / v_total as f32 } else { 0.0 };
    (h_sym, v_sym)
}

/// Skeleton topology features via Zhang-Suen thinning.
/// Returns (branch_points / 10, endpoints / 10), both clamped to [0, 1].
fn compute_skeleton_features(ink_mask: &[bool], w: usize, h: usize) -> (f32, f32) {
    if w < 3 || h < 3 {
        return (0.0, 0.0);
    }

    // Copy mask to mutable binary image for thinning
    let mut img: Vec<u8> = ink_mask.iter().map(|&b| if b { 1u8 } else { 0u8 }).collect();

    // Zhang-Suen thinning algorithm
    loop {
        let mut changed = false;

        // Step 1
        let mut to_remove = Vec::new();
        for y in 1..h - 1 {
            for x in 1..w - 1 {
                if img[y * w + x] == 0 { continue; }
                let p2 = img[(y - 1) * w + x] as i32;
                let p3 = img[(y - 1) * w + (x + 1)] as i32;
                let p4 = img[y * w + (x + 1)] as i32;
                let p5 = img[(y + 1) * w + (x + 1)] as i32;
                let p6 = img[(y + 1) * w + x] as i32;
                let p7 = img[(y + 1) * w + (x - 1)] as i32;
                let p8 = img[y * w + (x - 1)] as i32;
                let p9 = img[(y - 1) * w + (x - 1)] as i32;

                let neighbors = p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9;
                if neighbors < 2 || neighbors > 6 { continue; }

                // Count 0→1 transitions in the ordered sequence p2..p9..p2
                let seq = [p2, p3, p4, p5, p6, p7, p8, p9];
                let mut transitions = 0;
                for i in 0..8 {
                    if seq[i] == 0 && seq[(i + 1) % 8] == 1 {
                        transitions += 1;
                    }
                }
                if transitions != 1 { continue; }

                // Step 1 conditions: p2*p4*p6 == 0 && p4*p6*p8 == 0
                if p2 * p4 * p6 != 0 || p4 * p6 * p8 != 0 { continue; }
                to_remove.push(y * w + x);
            }
        }
        for idx in &to_remove {
            img[*idx] = 0;
            changed = true;
        }

        // Step 2
        let mut to_remove = Vec::new();
        for y in 1..h - 1 {
            for x in 1..w - 1 {
                if img[y * w + x] == 0 { continue; }
                let p2 = img[(y - 1) * w + x] as i32;
                let p3 = img[(y - 1) * w + (x + 1)] as i32;
                let p4 = img[y * w + (x + 1)] as i32;
                let p5 = img[(y + 1) * w + (x + 1)] as i32;
                let p6 = img[(y + 1) * w + x] as i32;
                let p7 = img[(y + 1) * w + (x - 1)] as i32;
                let p8 = img[y * w + (x - 1)] as i32;
                let p9 = img[(y - 1) * w + (x - 1)] as i32;

                let neighbors = p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9;
                if neighbors < 2 || neighbors > 6 { continue; }

                let seq = [p2, p3, p4, p5, p6, p7, p8, p9];
                let mut transitions = 0;
                for i in 0..8 {
                    if seq[i] == 0 && seq[(i + 1) % 8] == 1 {
                        transitions += 1;
                    }
                }
                if transitions != 1 { continue; }

                // Step 2 conditions: p2*p4*p8 == 0 && p2*p6*p8 == 0
                if p2 * p4 * p8 != 0 || p2 * p6 * p8 != 0 { continue; }
                to_remove.push(y * w + x);
            }
        }
        for idx in &to_remove {
            img[*idx] = 0;
            changed = true;
        }

        if !changed { break; }
    }

    // Count endpoints (1 neighbor) and branch points (≥3 neighbors)
    let mut endpoints = 0u32;
    let mut branch_pts = 0u32;
    for y in 1..h - 1 {
        for x in 1..w - 1 {
            if img[y * w + x] == 0 { continue; }
            let mut neighbors = 0u32;
            for dy in -1i32..=1 {
                for dx in -1i32..=1 {
                    if dx == 0 && dy == 0 { continue; }
                    let ny = (y as i32 + dy) as usize;
                    let nx = (x as i32 + dx) as usize;
                    if img[ny * w + nx] == 1 {
                        neighbors += 1;
                    }
                }
            }
            if neighbors == 1 { endpoints += 1; }
            if neighbors >= 3 { branch_pts += 1; }
        }
    }

    ((branch_pts as f32 / 10.0).min(1.0), (endpoints as f32 / 10.0).min(1.0))
}

/// Corner count using boundary direction changes.
/// Walks the ink boundary and counts points where direction changes sharply.
fn compute_corner_count(ink_mask: &[bool], w: usize, h: usize) -> f32 {
    if w < 3 || h < 3 {
        return 0.0;
    }

    // Collect boundary pixels (ink pixels with at least one non-ink 4-neighbor)
    let mut boundary: Vec<(usize, usize)> = Vec::new();
    for y in 0..h {
        for x in 0..w {
            if !ink_mask[y * w + x] { continue; }
            let mut on_boundary = false;
            for (dx, dy) in &[(-1i32, 0i32), (1, 0), (0, -1), (0, 1)] {
                let nx = x as i32 + dx;
                let ny = y as i32 + dy;
                if nx < 0 || ny < 0 || (nx as usize) >= w || (ny as usize) >= h {
                    on_boundary = true;
                    break;
                }
                if !ink_mask[ny as usize * w + nx as usize] {
                    on_boundary = true;
                    break;
                }
            }
            if on_boundary {
                boundary.push((x, y));
            }
        }
    }

    if boundary.len() < 5 {
        return 0.0;
    }

    // Simple corner detection: for each boundary pixel, look at neighbors
    // in the boundary that are within distance 3 and measure angle change.
    // More practical approach: count pixels where the local curvature is high
    // using a simple method based on the area of the triangle formed by
    // a point and its k-neighbors on the boundary.
    //
    // Use a simpler approach: count ink pixels that have exactly 1 or 2
    // diagonal ink neighbors but form an L-shape (corner of the glyph outline).
    let mut corners = 0u32;
    for y in 1..h - 1 {
        for x in 1..w - 1 {
            if !ink_mask[y * w + x] { continue; }
            // Check if this is a boundary pixel
            let up = if y > 0 { ink_mask[(y - 1) * w + x] } else { false };
            let down = if y + 1 < h { ink_mask[(y + 1) * w + x] } else { false };
            let left = if x > 0 { ink_mask[y * w + (x - 1)] } else { false };
            let right = if x + 1 < w { ink_mask[y * w + (x + 1)] } else { false };

            // L-shape patterns: exactly 2 adjacent cardinal neighbors that are
            // perpendicular (forming a corner)
            let cardinal = [up, right, down, left];
            let n_cardinal: usize = cardinal.iter().filter(|&&b| b).count();
            if n_cardinal != 2 { continue; }

            // Check if the two neighbors are perpendicular (not opposite)
            let is_corner = (up && right) || (right && down) || (down && left) || (left && up);
            if is_corner {
                // Check the diagonal to confirm it's a true corner (no diagonal fill)
                let diag_filled = match (up, right, down, left) {
                    (true, true, _, _) => ink_mask[(y - 1) * w + (x + 1)],
                    (_, true, true, _) => ink_mask[(y + 1) * w + (x + 1)],
                    (_, _, true, true) => ink_mask[(y + 1) * w + (x - 1)],
                    (true, _, _, true) => ink_mask[(y - 1) * w + (x - 1)],
                    _ => true,
                };
                if !diag_filled {
                    corners += 1;
                }
            }
        }
    }

    (corners as f32 / 20.0).min(1.0)
}

/// Ink density in each quadrant (TL, TR, BL, BR).
fn compute_quadrant_density(ink_mask: &[bool], w: usize, h: usize) -> [f32; 4] {
    if w == 0 || h == 0 {
        return [0.0; 4];
    }
    let mid_x = w / 2;
    let mid_y = h / 2;

    let mut counts = [0u32; 4];  // TL, TR, BL, BR
    let mut areas = [0u32; 4];

    for y in 0..h {
        for x in 0..w {
            let q = if y < mid_y {
                if x < mid_x { 0 } else { 1 }
            } else {
                if x < mid_x { 2 } else { 3 }
            };
            areas[q] += 1;
            if ink_mask[y * w + x] {
                counts[q] += 1;
            }
        }
    }

    let mut density = [0.0f32; 4];
    for i in 0..4 {
        density[i] = if areas[i] > 0 { counts[i] as f32 / areas[i] as f32 } else { 0.0 };
    }
    density
}

/// Linearly resample a 1-D signal to `n` bins.
fn resample(src: &[f32], n: usize) -> [f32; PROFILE_BINS] {
    let mut out = [0.0f32; PROFILE_BINS];
    if src.is_empty() || n == 0 {
        return out;
    }
    let src_len = src.len() as f32;
    for i in 0..n {
        let pos = i as f32 * (src_len - 1.0) / (n as f32 - 1.0).max(1.0);
        let lo = pos.floor() as usize;
        let hi = (lo + 1).min(src.len() - 1);
        let frac = pos - lo as f32;
        out[i] = src[lo] * (1.0 - frac) + src[hi] * frac;
    }
    out
}

// ---------------------------------------------------------------------------
// Character index
// ---------------------------------------------------------------------------

/// Per-font feature for a single character.
#[derive(Debug, Clone)]
pub struct FontCharEntry {
    pub font_name: String,
    pub features: CharFeatures,
}

/// The full index: for each indexed character, a list of (font, features)
/// plus flat per-character vectors for brute-force spatial lookup.
#[derive(Debug)]
pub struct CharIndex {
    /// char → Vec<(font_name, features)> — raw entries for serialization + merge
    pub entries: HashMap<char, Vec<FontCharEntry>>,
    /// Fonts that were scanned but produced no indexable characters.
    pub skipped_fonts: std::collections::HashSet<String>,
    /// Ordered font name table: font_id → font_name
    font_names_table: Vec<String>,
    /// Per-character flat vectors: (font_id, weighted_features) for brute-force search
    flat_vecs: HashMap<char, Vec<(usize, [f32; FEAT_LEN])>>,
    /// Per-character per-dimension standard deviations (for diagnostics)
    dim_sigmas: HashMap<char, [f32; FEAT_LEN]>,
}

impl Clone for CharIndex {
    fn clone(&self) -> Self {
        let mut idx = CharIndex {
            entries: self.entries.clone(),
            skipped_fonts: self.skipped_fonts.clone(),
            font_names_table: Vec::new(),
            flat_vecs: HashMap::new(),
            dim_sigmas: HashMap::new(),
        };
        idx.rebuild_vecs();
        idx
    }
}

impl CharIndex {
    /// Build flat per-character vectors and compute per-dimension σ from entries.
    pub fn rebuild_vecs(&mut self) {
        // Build font name → id mapping
        let mut name_set: std::collections::HashSet<String> = std::collections::HashSet::new();
        for entries in self.entries.values() {
            for e in entries {
                name_set.insert(e.font_name.clone());
            }
        }
        let mut names: Vec<String> = name_set.into_iter().collect();
        names.sort();
        self.font_names_table = names;
        let name_to_id: HashMap<&str, usize> = self.font_names_table.iter()
            .enumerate()
            .map(|(i, n)| (n.as_str(), i))
            .collect();

        self.flat_vecs.clear();
        self.dim_sigmas.clear();

        for (c, char_entries) in &self.entries {
            if char_entries.is_empty() {
                continue;
            }

            // Build flat vec of (font_id, weighted_features), deduplicating
            // identical weighted vectors.  OT variants that render the same glyph
            // produce identical features; keeping them wastes memory and dilutes
            // between-font variance.  Variants that genuinely differ are preserved.
            let mut points: Vec<(usize, [f32; FEAT_LEN])> = Vec::with_capacity(char_entries.len());
            let mut seen: std::collections::HashSet<[u32; FEAT_LEN]> = std::collections::HashSet::new();

            for e in char_entries {
                let weighted = e.features.weighted();
                // Round to f32 bit pattern for dedup (exact match)
                let key: [u32; FEAT_LEN] = {
                    let mut k = [0u32; FEAT_LEN];
                    for (i, &v) in weighted.iter().enumerate() {
                        k[i] = v.to_bits();
                    }
                    k
                };
                if seen.insert(key) {
                    if let Some(&font_id) = name_to_id.get(e.font_name.as_str()) {
                        points.push((font_id, weighted));
                    }
                }
            }

            if points.is_empty() {
                continue;
            }

            // Compute per-dimension mean and σ
            let n = points.len() as f32;
            let mut means = [0.0f32; FEAT_LEN];
            for (_, w) in &points {
                for d in 0..FEAT_LEN {
                    means[d] += w[d];
                }
            }
            for d in 0..FEAT_LEN {
                means[d] /= n;
            }

            let mut sigmas = [0.0f32; FEAT_LEN];
            for (_, w) in &points {
                for d in 0..FEAT_LEN {
                    let diff = w[d] - means[d];
                    sigmas[d] += diff * diff;
                }
            }
            for d in 0..FEAT_LEN {
                sigmas[d] = (sigmas[d] / n).sqrt();
            }

            self.dim_sigmas.insert(*c, sigmas);
            self.flat_vecs.insert(*c, points);
        }
    }
}

/// Build the per-character index for all provided fonts.
/// Glyph override map for OT variant entries (e.g. smcp, onum).
/// Maps character → overridden glyph ID so the CI renders the correct variant glyph.
pub type GlyphOverrides = Option<Vec<(char, u16)>>;

/// Resolve glyph ID for a character, applying OT variant overrides when present.
/// Falls back to the font's default cmap lookup if no override exists for this character.
pub fn resolve_glyph<F: ab_glyph::Font>(font: &F, ch: char, overrides: Option<&[(char, u16)]>) -> ab_glyph::GlyphId {
    if let Some(ovs) = overrides {
        if let Some(&(_, gid)) = ovs.iter().find(|(c, _)| *c == ch) {
            return ab_glyph::GlyphId(gid);
        }
    }
    font.glyph_id(ch)
}

pub fn build_char_index(font_paths: &[(String, std::path::PathBuf, GlyphOverrides)]) -> CharIndex {
    use rayon::prelude::*;

    let chars = indexed_chars();

    // Per-font result: Vec of (char, entry) pairs, plus font_name if skipped.
    struct FontResult {
        char_entries: Vec<(char, FontCharEntry)>,
        skipped: Option<String>,
    }

    // Phase 1: process each font in parallel (CPU-bound: render + features).
    // Font bytes are loaded from disk per-thread and dropped after processing,
    // so only ~N fonts are in memory at once (N = rayon thread count).
    let results: Vec<FontResult> = font_paths.par_iter().map(|(font_name, font_path, glyph_overrides)| {
        let font_data = match std::fs::read(font_path) {
            Ok(d) => d,
            Err(_) => {
                return FontResult {
                    char_entries: Vec::new(),
                    skipped: Some(font_name.clone()),
                };
            }
        };
        let font = match FontRef::try_from_slice(&font_data) {
            Ok(f) => f,
            Err(_) => {
                return FontResult {
                    char_entries: Vec::new(),
                    skipped: Some(font_name.clone()),
                };
            }
        };

        // Build fast lookup for glyph overrides
        let override_map: HashMap<char, u16> = glyph_overrides
            .as_ref()
            .map(|v| v.iter().cloned().collect())
            .unwrap_or_default();

        let xh_ratio = compute_xh_cap_ratio(&font);
        let serif = compute_font_serif_score(&font);

        let mut char_entries = Vec::with_capacity(chars.len());
        for &c in chars {
            // Use override glyph ID if this variant changes this character,
            // otherwise fall back to default glyph.
            let img = if let Some(&gid) = override_map.get(&c) {
                render_glyph_normalised(&font, ab_glyph::GlyphId(gid))
            } else {
                render_char_normalised(&font, c)
            };
            if let Some(img) = img {
                if let Some(mut feats) = compute_features(&img) {
                    feats.xh_cap_ratio = xh_ratio;
                    feats.serif_score = serif;
                    char_entries.push((c, FontCharEntry {
                        font_name: font_name.clone(),
                        features: feats,
                    }));
                }
            }
        }

        let skipped = if char_entries.is_empty() { Some(font_name.clone()) } else { None };
        FontResult { char_entries, skipped }
    }).collect();

    // Phase 2: merge results (sequential, fast — just moving Vecs)
    let mut entries: HashMap<char, Vec<FontCharEntry>> = HashMap::new();
    for c in chars {
        entries.insert(*c, Vec::with_capacity(font_paths.len()));
    }
    let mut skipped_fonts: std::collections::HashSet<String> = std::collections::HashSet::new();

    for result in results {
        if let Some(name) = result.skipped {
            skipped_fonts.insert(name);
        }
        for (c, entry) in result.char_entries {
            entries.entry(c).or_default().push(entry);
        }
    }

    let mut index = CharIndex {
        entries,
        skipped_fonts,
        font_names_table: Vec::new(),
        flat_vecs: HashMap::new(),
        dim_sigmas: HashMap::new(),
    };
    index.rebuild_vecs();
    index
}

/// Render a single character in `font` at `NORM_H` ink height.
pub fn render_char_normalised<F: Font>(font: &F, c: char) -> Option<GrayImage> {
    render_glyph_normalised(font, font.glyph_id(c))
}

/// Render a specific glyph ID, normalised to NORM_H with tight ink crop.
pub fn render_glyph_normalised<F: Font>(font: &F, gid: ab_glyph::GlyphId) -> Option<GrayImage> {
    if gid.0 == 0 {
        return None;
    }

    let ref_h = 200.0f32;
    let ref_scale = PxScale::from(ref_h);
    let sf_ref = font.as_scaled(ref_scale);

    let glyph = gid.with_scale_and_position(ref_scale, point(0.0, sf_ref.ascent()));
    let outlined = font.outline_glyph(glyph)?;
    let bounds = outlined.px_bounds();
    let ink_h_ref = bounds.max.y - bounds.min.y;
    if ink_h_ref < 1.0 {
        return None;
    }

    let target_scale = ref_h * (NORM_H as f32 / ink_h_ref);
    let scale = PxScale::from(target_scale);
    let sf = font.as_scaled(scale);

    let glyph2 = gid.with_scale_and_position(scale, point(0.0, sf.ascent()));
    let outlined2 = font.outline_glyph(glyph2)?;
    let b2 = outlined2.px_bounds();

    let img_w = (b2.max.x - b2.min.x).ceil() as u32 + 2;
    let img_h = (b2.max.y - b2.min.y).ceil() as u32 + 2;
    if img_w == 0 || img_h == 0 || img_w > 500 || img_h > 500 {
        return None;
    }

    let mut canvas = GrayImage::from_pixel(img_w, img_h, Luma([255u8]));
    let ox = b2.min.x.floor() as i32;
    let oy = b2.min.y.floor() as i32;

    outlined2.draw(|gx, gy, cov| {
        let px = gx as i32 + (b2.min.x.floor() as i32) - ox + 1;
        let py = gy as i32 + (b2.min.y.floor() as i32) - oy + 1;
        if px >= 0 && py >= 0 && (px as u32) < img_w && (py as u32) < img_h {
            let val = (255.0 * (1.0 - cov)) as u8;
            let cur = canvas.get_pixel(px as u32, py as u32).0[0];
            canvas.put_pixel(px as u32, py as u32, Luma([cur.min(val)]));
        }
    });

    // Run through the same normalize path the scan side uses, so both
    // index-time and scan-time images have identical geometry (tight ink
    // crop, 1px padding, resized to exactly NORM_H).
    normalize_to_ink_bounds(&canvas)
}

// ---------------------------------------------------------------------------
// Shared normalisation: tight ink crop → NORM_H scale
// ---------------------------------------------------------------------------

pub fn normalize_to_ink_bounds(img: &GrayImage) -> Option<GrayImage> {
    let (w, h) = img.dimensions();
    if w == 0 || h == 0 {
        return None;
    }
    const THRESH: u8 = 200;
    let mut min_x = w;
    let mut max_x = 0u32;
    let mut min_y = h;
    let mut max_y = 0u32;
    for y in 0..h {
        for x in 0..w {
            if img.get_pixel(x, y).0[0] < THRESH {
                if x < min_x { min_x = x; }
                if x > max_x { max_x = x; }
                if y < min_y { min_y = y; }
                if y > max_y { max_y = y; }
            }
        }
    }
    if min_x > max_x || min_y > max_y {
        return None;
    }
    // Crop tightly to ink, then paste onto a white canvas with guaranteed
    // 1px padding on all sides — matching index-time render_char_normalised
    // which creates a canvas of (ink_w+2) × (ink_h+2).
    // Previous approach used saturating_sub which clipped at image boundary,
    // producing 0px padding when ink reached the edge of the raw slice.
    let ink_w = max_x - min_x + 1;
    let ink_h = max_y - min_y + 1;
    if ink_w < 1 || ink_h < 1 {
        return None;
    }
    let pad = 1u32;
    let canvas_w = ink_w + 2 * pad;
    let canvas_h = ink_h + 2 * pad;
    let mut canvas = GrayImage::from_pixel(canvas_w, canvas_h, Luma([255u8]));
    // Copy ink region into canvas at (pad, pad)
    for y in min_y..=max_y {
        for x in min_x..=max_x {
            let px = img.get_pixel(x, y);
            canvas.put_pixel(x - min_x + pad, y - min_y + pad, *px);
        }
    }
    let scaled_w = (canvas_w as f32 * NORM_H as f32 / canvas_h as f32).ceil() as u32;
    if scaled_w < 2 {
        return None;
    }
    Some(image::imageops::resize(
        &canvas,
        scaled_w,
        NORM_H,
        image::imageops::FilterType::Lanczos3,
    ))
}

// ---------------------------------------------------------------------------
// Character extraction from scan
// ---------------------------------------------------------------------------

/// Extract individual character crops from a scan line.
pub fn extract_line_chars<F: ab_glyph::Font>(
    page: &GrayImage,
    words: &[WordPlacement],
    line_height: u32,
    diag_seg_dir: Option<&std::path::Path>,
    diag_ref_font: Option<&F>,
) -> Vec<(char, GrayImage)> {
    if words.is_empty() || line_height == 0 {
        return Vec::new();
    }

    // Crop whole words (reliable bboxes from Tesseract) and split them
    // into individual characters using VP + seam carving.

    let mut sorted: Vec<&WordPlacement> = words
        .iter()
        .filter(|w| w.text.chars().count() >= MIN_WORD_LEN && w.width > 0)
        .collect();
    sorted.sort_by(|a, b| b.text.chars().count().cmp(&a.text.chars().count()));

    let mut char_counts: HashMap<char, usize> = HashMap::new();
    let mut results: Vec<(char, GrayImage)> = Vec::new();

    for (word_idx, word) in sorted.iter().enumerate() {
        let chars_in_word: Vec<char> = word.text.chars().filter(|c| is_indexed(*c)).collect();
        if chars_in_word.is_empty() {
            continue;
        }

        let need_any = chars_in_word.iter().any(|c| {
            char_counts.get(c).copied().unwrap_or(0) < 2
        });
        if !need_any {
            continue;
        }

        let wx = word.x_off;
        let wy = word.y_off;
        let ww = word.width;
        let wh = word.height;

        let (pw, ph) = page.dimensions();
        if wx >= pw || wy >= ph {
            continue;
        }

        let crop_w = ww.min(pw - wx);
        let crop_h = wh.min(ph - wy);
        if crop_w < 2 || crop_h < 2 {
            continue;
        }

        // Crop the word at Tesseract's bbox (reliable at word level).
        // Don't ink-expand or ink-trim — the bbox is already tight and
        // ink-trimming picks up stray text from adjacent lines.
        let word_img = image::imageops::crop_imm(page, wx, wy, crop_w, crop_h).to_image();

        // Debug: dump pre-segmentation word image
        if std::env::var("UNSCAN_DUMP_CROPS").is_ok() {
            let dump_dir = std::path::PathBuf::from("/tmp/unscan-crops");
            std::fs::create_dir_all(&dump_dir).ok();
            let fname = format!("word_{}.png", word.text.replace(' ', "_").replace('/', "_"));
            word_img.save(dump_dir.join(&fname)).ok();
        }

        let (_word_w, word_h) = word_img.dimensions();
        let all_chars: Vec<char> = word.text.chars().collect();

        let ((boundaries, seam_path_map), word_diag_dir) = if let Some(ddir) = diag_seg_dir {
            let word_slug = crate::seg_diag::sanitize_text(&word.text);
            let word_dir = ddir.join(format!("word_{:03}_{}", word_idx, word_slug));
            (segment_characters_diag(&word_img, all_chars.len(), &word_dir, &word.text),
             Some(word_dir))
        } else {
            (segment_characters(&word_img, all_chars.len()), None)
        };

        extract_chars_from_boundaries(
            &word_img, &all_chars, &boundaries, &seam_path_map, word_h,
            &mut char_counts, &mut results,
            word_diag_dir.as_deref(),
            diag_ref_font,
        );
    }

    results
}

fn extract_chars_from_boundaries<F: ab_glyph::Font>(
    word_img: &GrayImage,
    chars: &[char],
    boundaries: &[u32],
    seam_paths: &HashMap<u32, Vec<u32>>,
    crop_h: u32,
    char_counts: &mut HashMap<char, usize>,
    results: &mut Vec<(char, GrayImage)>,
    diag_dir: Option<&std::path::Path>,
    diag_ref_font: Option<&F>,
) {
    let (ww, _wh) = word_img.dimensions();

    if let Some(ddir) = diag_dir {
        let _ = std::fs::create_dir_all(ddir.join("chars"));
    }

    for (i, &c) in chars.iter().enumerate() {
        if !is_indexed(c) {
            continue;
        }
        if char_counts.get(&c).copied().unwrap_or(0) >= 3 {
            continue;
        }

        if i + 1 >= boundaries.len() {
            break;
        }
        let b_left = boundaries[i];
        let b_right = boundaries[i + 1];

        // Look up seam paths for left and right boundaries.
        let left_seam = seam_paths.get(&b_left);
        let right_seam = seam_paths.get(&b_right);

        // Compute crop x-range: extend to the full seam extent so we
        // capture all pixels that belong to this character.
        let x0 = if let Some(sp) = left_seam {
            sp.iter().copied().min().unwrap_or(b_left).min(b_left)
        } else {
            b_left
        }.min(ww);

        let x1 = if let Some(sp) = right_seam {
            sp.iter().copied().max().unwrap_or(b_right).max(b_right).saturating_add(1)
        } else {
            b_right
        }.min(ww);

        if x1 <= x0 || (x1 - x0) < 2 {
            continue;
        }

        let mut char_crop = image::imageops::crop_imm(word_img, x0, 0, x1 - x0, crop_h).to_image();

        // Mask out pixels on the wrong side of seam boundaries.
        let crop_w = x1 - x0;
        if left_seam.is_some() || right_seam.is_some() {
            for y in 0..crop_h.min(char_crop.height()) {
                // Left seam: blank pixels left of the seam path
                if let Some(sp) = left_seam {
                    if let Some(&seam_x) = sp.get(y as usize) {
                        // seam_x is in word-image coords; convert to crop coords
                        let limit = seam_x.saturating_sub(x0);
                        for cx in 0..limit.min(crop_w) {
                            char_crop.put_pixel(cx, y, image::Luma([255u8]));
                        }
                    }
                }
                // Right seam: blank pixels right of the seam path
                if let Some(sp) = right_seam {
                    if let Some(&seam_x) = sp.get(y as usize) {
                        let start = seam_x.saturating_sub(x0);
                        for cx in start..crop_w {
                            char_crop.put_pixel(cx, y, image::Luma([255u8]));
                        }
                    }
                }
            }
        }

        let scaled = match normalize_to_ink_bounds(&char_crop) {
            Some(img) => img,
            None => continue,
        };

        // Diag: save the exact image that CI searches against
        if let Some(ddir) = diag_dir {
            let label = crate::seg_diag::sanitize_char(c);
            let fname = format!("{:02}_{}.png", i, label);
            let _ = scaled.save(ddir.join("chars").join(fname));

            // Also save index-time render from reference font for comparison
            if let Some(ref_font) = diag_ref_font {
                if let Some(ref_img) = render_char_normalised(ref_font, c) {
                    let ref_fname = format!("{:02}_{}_ref.png", i, label);
                    let _ = ref_img.save(ddir.join("chars").join(ref_fname));
                }
            }
        }

        results.push((c, scaled));
        *char_counts.entry(c).or_insert(0) += 1;
    }
}

// ---------------------------------------------------------------------------
// Matching — k-d tree based
// ---------------------------------------------------------------------------

/// Search result from the k-d tree for a single character.
/// Contains font candidates within the tolerance radius.
#[derive(Debug, Clone)]
pub struct CharSearchResult {
    /// The character queried
    pub ch: char,
    /// Candidate fonts within tolerance: (font_name, cosine_similarity)
    pub candidates: Vec<(String, f32)>,
    /// The search radius used
    pub radius: f32,
    /// Number of fonts within the radius
    pub n_within_radius: usize,
}

/// Search the index for candidate fonts matching the given character crops.
///
/// This is the single shared search function used by both the pipeline and tests.
///
/// # Scoring: geometric mean of k-d tree distances
///
/// Each character's k-d tree gives us a squared Euclidean distance d²ᵢ for
/// font F in the 57-dimensional weighted feature space.  Under the null
/// hypothesis (random font), these distances follow a scaled χ² distribution
/// — fonts that are genuinely similar will have consistently small distances
/// across multiple independent character observations.
///
/// We aggregate via the **geometric mean of distances**:
///
/// ```text
///     score(F) = exp( (1/N) · Σᵢ log(d²ᵢ + ε) )
/// ```
///
/// This is equivalent to multiplying per-character p-values (Fisher's method)
/// in log space.  It has two key properties:
///
/// 1. **Multiplicative sensitivity:** a font that's close on 14 of 15 chars
///    but far on 1 gets a much worse score than a font that's moderately close
///    on all 15.  One bad character tanks the geometric mean — this naturally
///    penalizes the "619 fonts within 2× on 'e'" problem because those fonts
///    will have large distances on other characters.
///
/// 2. **No arbitrary union:** we don't union per-character candidate sets.
///    Instead, we collect (font_id, d²) pairs per character, then score every
///    font that appears in ≥ quorum characters.  Fonts appearing in only 1-2
///    character neighborhoods are discarded — they're statistical noise.
///
/// The quorum threshold (currently ≥ 50% of queried characters) acts as a
/// lightweight pre-filter before the geometric mean calculation.  A font must
/// be a plausible match on at least half the characters to be considered.
///
/// Returns top `top_n` fonts by geometric-mean distance (ascending = best).
/// The returned f32 score is negated log-geometric-mean so that higher = better,
/// matching the convention expected by downstream callers.
/// Per-character CI detail, collected from the real search_candidates loop.
#[derive(Debug, Clone)]
pub struct CharCiDetail {
    pub ch: char,
    pub crop_index: usize,
    pub min_dist_sq: f32,
    pub passed_gate: bool,
    /// Top-3 nearest fonts (name, dist_sq).
    pub nearest: Vec<(String, f32)>,
    /// When the OCR correction gate fires, the original OCR character
    /// that was replaced.  `ch` then holds the corrected character,
    /// and `nearest`/`min_dist_sq` reflect the corrected char's CI.
    pub ocr_corrected_from: Option<char>,
    /// Best alternative character considered (even if correction gate
    /// didn't fire).  Always the char with the lowest distance among
    /// all confusables/alternatives tested, if any were tested.
    pub best_alt_char: Option<char>,
    /// Distance of the best alternative character.
    pub best_alt_dist: Option<f32>,
}

/// Result of `search_candidates`: ranked font scores + per-character CI detail.
#[derive(Debug)]
pub struct CiSearchResult {
    pub scores: Vec<(String, f32)>,
    pub char_detail: Vec<CharCiDetail>,
}

pub fn search_candidates(
    index: &CharIndex,
    char_crops: &[(char, GrayImage)],
    thoroughness: f32,
) -> CiSearchResult {
    if char_crops.is_empty() {
        return CiSearchResult { scores: Vec::new(), char_detail: Vec::new() };
    }

    // Pre-compute weighted feature vectors for all crops
    let crop_feats: Vec<(usize, char, [f32; FEAT_LEN])> = char_crops
        .iter()
        .enumerate()
        .filter_map(|(i, (c, img))| {
            compute_features(img).map(|f| (i, *c, f.weighted()))
        })
        .collect();

    if crop_feats.is_empty() {
        return CiSearchResult { scores: Vec::new(), char_detail: Vec::new() };
    }

    let n_chars = crop_feats.len();
    // Quorum: font must appear in at least half the character neighborhoods.
    let quorum = ((n_chars + 1) / 2).max(1) as f32 / thoroughness;
    let quorum = (quorum.ceil() as usize).max(1);


    // For each character, find nearby fonts and record their distances.
    // font_id → Vec<(log_dist, weight)>
    let mut font_log_dists: HashMap<usize, Vec<(f32, f32)>> = HashMap::new();
    let mut quality_gate_pass = 0usize;
    let mut quality_gate_fail = 0usize;
    let mut no_tree = 0usize;
    let mut char_detail: Vec<CharCiDetail> = Vec::with_capacity(crop_feats.len());

    for (crop_idx, c, query_feat) in &crop_feats {
        let weight = char_weight(*c);

        // Find nearest neighbor + everything within (2.5 × thoroughness)× that distance.
        let hits: Vec<(usize, f32)> = if let Some(points) = index.flat_vecs.get(c) {
            nearest_within_factor_brute(points, query_feat, 2.5 * thoroughness)
        } else {
            no_tree += 1;
            continue;
        };

        let min_dist_sq = hits.iter().map(|(_, d)| *d).fold(f32::INFINITY, f32::min);

        // ── OCR correction gate ─────────────────────────────────────
        // If the OCR char's best distance is suspiciously large AND 10×
        // worse than the best distance under a different character, the
        // OCR label is likely mangled (e.g. Q→dingbat at 50-100×).
        // Substitute the alternative. Only fires for extreme mismatches,
        // not style confusion (e vs c at 2-5×).
        let mut effective_hits = hits;
        let mut effective_min = min_dist_sq;
        let mut effective_ch: Option<char> = None;
        let mut best_alt_char: Option<char> = None;
        let mut best_alt_dist: Option<f32> = None;

        if min_dist_sq > 0.1 {
            // Only check alternatives when OCR match is already poor.
            // Test confusable characters that OCR commonly swaps.
            let confusables: &[char] = match c {
                'l' | 'I' | '1' | '|' => &['l', 'I', '1'],
                'O' | '0' | 'Q' => &['O', '0', 'Q', 'o'],
                'o' | 'c' | 'e' => &['o', 'c', 'e'],
                'S' | '5' | 's' => &['S', '5', 's'],
                'B' | '8' => &['B', '8'],
                'Z' | '2' => &['Z', '2'],
                'b' | 'd' | 'p' | 'q' => &['b', 'd', 'p', 'q'],
                'n' | 'h' | 'u' => &['n', 'h', 'u', 'm', 'r'],
                _ => &[],
            };
            // Also check every indexed char if the distance is truly catastrophic
            let check_all = min_dist_sq > 0.5;
            let chars_to_check: Vec<char> = if check_all {
                indexed_chars().iter().filter(|&&alt| alt != *c).copied().collect()
            } else {
                confusables.iter().filter(|&&alt| alt != *c).copied().collect()
            };


            for alt_c in &chars_to_check {
                if let Some(alt_points) = index.flat_vecs.get(alt_c) {
                    let alt_hits = nearest_within_factor_brute(alt_points, query_feat, 2.5 * thoroughness);
                    let alt_min = alt_hits.iter().map(|(_, d)| *d).fold(f32::INFINITY, f32::min);
                    // Track best alt regardless of correction gate
                    if best_alt_dist.map_or(true, |d| alt_min < d) {
                        best_alt_char = Some(*alt_c);
                        best_alt_dist = Some(alt_min);
                    }
                    if alt_min < effective_min && min_dist_sq > alt_min * 10.0 {
                        effective_hits = alt_hits;
                        effective_min = alt_min;
                        effective_ch = Some(*alt_c);
                    }
                }
            }
        }

        let hits = effective_hits;
        let min_dist_sq = effective_min;

        // Quality gate: scaled by thoroughness (default 0.5, higher = more permissive)
        let passed_gate = min_dist_sq <= 0.5 * thoroughness;
        if !passed_gate {
            quality_gate_fail += 1;
        } else {
            quality_gate_pass += 1;
        }

        // Collect per-char detail from the real search
        let mut sorted_hits = hits.clone();
        sorted_hits.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
        let nearest: Vec<(String, f32)> = sorted_hits.iter()
            .take(3)
            .filter_map(|(font_id, d)| {
                let name = index.font_names_table.get(*font_id)?;
                Some((name.clone(), *d))
            })
            .collect();
        char_detail.push(CharCiDetail {
            ch: effective_ch.unwrap_or(*c),
            crop_index: *crop_idx,
            min_dist_sq,
            passed_gate,
            nearest,
            ocr_corrected_from: effective_ch.map(|_| *c),
            best_alt_char,
            best_alt_dist,
        });

        if !passed_gate {
            continue;
        }

        for (font_id, dist_sq) in &hits {

            // ε = 1e-10 avoids log(0) for self-matches / identical OT variants
            let log_d = (dist_sq + 1e-10_f32).ln();
            font_log_dists.entry(*font_id).or_default().push((log_d, weight));
        }
    }

    eprintln!(
        "  CI: {} crops, {} pass gate, {} fail gate, {} no_tree → {} fonts in voting",
        crop_feats.len(),
        quality_gate_pass,
        quality_gate_fail,
        no_tree,
        font_log_dists.len(),
    );

    // Aggregate: geometric mean of distances per font.
    //
    // For fonts missing from some characters, we penalize with a large
    // distance (the penalty is the max log-distance seen across all fonts
    // for that character slot).  But first we enforce the quorum — fonts
    // appearing in fewer than ceil(n/2) characters are dropped entirely.
    let penalty_log_dist = 0.0_f32; // log(1.0) = 0; i.e. d²=1.0, very far in normalized space

    // Keep a backup for the "at least 1" fallback (quorum may drop everything)
    let font_log_dists_backup: HashMap<usize, Vec<(f32, f32)>> = font_log_dists.clone();

    let mut scores: Vec<(String, f32)> = font_log_dists
        .into_iter()
        .filter_map(|(font_id, log_dists)| {
            let matched = log_dists.len();
            // Quorum gate: must appear in enough character neighborhoods
            if matched < quorum {
                return None;
            }
            let name = index.font_names_table.get(font_id)?.clone();

            // Weighted mean of log-distances.
            // Pad missing characters with the penalty distance.
            let mut total_weight = 0.0_f32;
            let mut weighted_sum = 0.0_f32;
            for (ld, w) in &log_dists {
                weighted_sum += ld * w;
                total_weight += w;
            }
            // Penalty for missing characters
            for _ in matched..n_chars {
                weighted_sum += penalty_log_dist * 1.0;
                total_weight += 1.0;
            }

            let mean_log_dist = weighted_sum / total_weight.max(1e-9);
            // Negate so higher = better (smaller distance = better match)
            let score = -mean_log_dist;
            Some((name, score))
        })
        .collect();

    scores.retain(|(_, s)| s.is_finite());

    // OT variants (smcp, onum, salt, etc.) are treated as first-class fonts.
    // They produce genuinely different glyphs and should compete on merit.

    // Sort descending (higher = better = closer match)
    // Tiebreaker: prefer base (untagged) font over OT variants when scores
    // are equal — avoids random variant wins from floating-point noise.
    scores.sort_by(|a, b| {
        b.1.partial_cmp(&a.1)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.0.contains('|').cmp(&b.0.contains('|')))
    });

    // ── Cross-family Latin clone dedup ───────────────────────────────
    // Many font families embed the same Latin glyphs from a shared source.
    // E.g., ALL Noto* fonts (NotoSans, NotoSansDisplay, NotoTraditionalNushu,
    // NotoSansMath, NotoSansSymbols, etc.) share the same NotoSans Latin
    // outlines.  Font metrics (ascent/descent/em) differ, producing slightly
    // different feature-vector normalizations and scores (Δ ~0.01–0.03),
    // but the glyphs are identical.
    //
    // Two-pass dedup:
    //   1. Score-based: merge adjacent (sorted) entries within ε=1e-5 (exact clones)
    //   2. Path-based: group Noto sans-serif fonts into one family slot
    //
    // In each group, keep the entry with the best score.
    {
        // Pass 1: score-epsilon dedup
        let eps = 1e-5_f32;
        let mut deduped: Vec<(String, f32)> = Vec::new();
        for (name, score) in &scores {
            if let Some(last) = deduped.last_mut() {
                if (score - last.1).abs() < eps {
                    if name.len() < last.0.len() {
                        *last = (name.clone(), *score);
                    }
                    continue;
                }
            }
            deduped.push((name.clone(), *score));
        }
        scores = deduped;

        // Pass 2: Noto family grouping
        // All /noto/Noto* sans-serif fonts → "NotoSans" group
        // All /noto/NotoSerif* fonts → "NotoSerif" group
        // Keep best (highest score) per group; non-Noto fonts pass through.
        fn noto_group(name: &str) -> Option<&'static str> {
            // Match font paths containing "/noto/" or font names starting with "Noto"
            let is_noto = name.contains("/noto/") || {
                // Extract basename
                let base = name.rsplit('/').next().unwrap_or(name);
                base.starts_with("Noto")
            };
            if !is_noto { return None; }
            // Check serif vs sans
            let base = name.rsplit('/').next().unwrap_or(name);
            if base.starts_with("NotoSerif") {
                Some("__noto_serif__")
            } else if base.starts_with("NotoSansMono") || base.starts_with("NotoMono") {
                Some("__noto_mono__")
            } else {
                // Everything else: NotoSans*, NotoSansDisplay*, NotoTraditionalNushu*, etc.
                Some("__noto_sans__")
            }
        }

        let mut best_by_group: HashMap<&str, (usize, f32)> = HashMap::new();
        for (i, (name, score)) in scores.iter().enumerate() {
            if let Some(group) = noto_group(name) {
                let entry = best_by_group.entry(group).or_insert((i, *score));
                if *score > entry.1 {
                    *entry = (i, *score);
                }
            }
        }

        let mut drop_indices: std::collections::HashSet<usize> = std::collections::HashSet::new();
        for (_group, (keep_idx, _)) in &best_by_group {
            for (i, (name, _)) in scores.iter().enumerate() {
                if noto_group(name).is_some() && i != *keep_idx {
                    drop_indices.insert(i);
                }
            }
        }

        if !drop_indices.is_empty() {
            let before = scores.len();
            scores = scores.into_iter().enumerate()
                .filter(|(i, _)| !drop_indices.contains(i))
                .map(|(_, v)| v)
                .collect();
            eprintln!("  CI: Noto family dedup {before} → {} fonts", scores.len());
        }
    }

    // ── Statistical cutoff: keep best + near-ties ────────────────────
    // CI is the recall stage — high recall, lower precision (no spacing
    // info).  We keep the top score and anything within k·σ of it.
    //
    // σ is computed on the top 50 scores only (the contender pool), not
    // the full distribution.  The full distribution has a long left tail
    // of clearly-wrong fonts that inflates σ and makes the cutoff too
    // generous.  The top-50 σ measures spread among actual contenders.
    //
    // k = 0.5 * thoroughness: default thoroughness=1.0 → k=0.5.
    // Higher thoroughness widens the window (more candidates, slower).
    if scores.len() >= 2 {
        let top_n = 50.min(scores.len());
        let vals: Vec<f32> = scores.iter().take(top_n).map(|(_, s)| *s).collect();
        let n = vals.len() as f32;
        let mean = vals.iter().sum::<f32>() / n;
        let variance = vals.iter().map(|v| (v - mean).powi(2)).sum::<f32>() / n;
        let sigma = variance.sqrt();
        let best = vals[0];
        let k = 0.5 * thoroughness;
        let cutoff = best - k * sigma;
        let before = scores.len();
        scores.retain(|(_, s)| *s >= cutoff);
        eprintln!(
            "  CI sigma cutoff: best={:.3} top50_σ={:.3} cutoff={:.3} → {} of {} kept",
            best, sigma, cutoff, scores.len(), before,
        );
    }

    // Guarantee at least 1 result: if quorum dropped everything, return the
    // single font with the best (lowest) average distance across whatever
    // characters it did appear in.
    if scores.is_empty() && !font_log_dists_backup.is_empty() {
        if let Some(best) = font_log_dists_backup
            .into_iter()
            .filter_map(|(font_id, log_dists)| {
                let name = index.font_names_table.get(font_id)?.clone();
                let total_weight: f32 = log_dists.iter().map(|(_, w)| w).sum();
                let weighted_sum: f32 = log_dists.iter().map(|(ld, w)| ld * w).sum();
                let mean = weighted_sum / total_weight.max(1e-9);
                Some((name, -mean))
            })
            .max_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal))
        {
            scores.push(best);
        }
    }

    CiSearchResult { scores, char_detail }
}

/// Compute per-character squared Euclidean distances from crop features to a
/// specific font's reference glyphs.  Used after the winner is determined so
/// the audit log can include per-char scores for the chosen font.
///
/// Returns `(char, crop_index, dist_sq)` for each crop that has features and
/// a matching reference glyph in the index.  Crops with no features or no
/// reference for that font are omitted.
pub fn per_char_distances(
    index: &CharIndex,
    font_key: &str,
    char_crops: &[(char, GrayImage)],
) -> Vec<(char, usize, f32)> {
    // Find the font_id for the requested key
    let font_id = match index.font_names_table.iter().position(|n| n == font_key) {
        Some(id) => id,
        None => return Vec::new(),
    };

    let mut result = Vec::with_capacity(char_crops.len());
    for (crop_idx, (ch, crop)) in char_crops.iter().enumerate() {
        let feats = match compute_features(crop) {
            Some(f) => f,
            None => continue,
        };
        let query = feats.weighted();

        // Find this font's weighted vector for this character
        if let Some(points) = index.flat_vecs.get(ch) {
            for (fid, ref_vec) in points {
                if *fid == font_id {
                    let d2 = squared_distance(&query, ref_vec);
                    result.push((*ch, crop_idx, d2));
                    break;
                }
            }
        }
    }
    result
}

// ---------------------------------------------------------------------------
// Serialisation (simple binary format)
// ---------------------------------------------------------------------------

/// Bump this whenever the feature vector, normalization, or serialization
/// layout changes. Stale caches auto-rebuild on mismatch.
const INDEX_VERSION: u32 = 7;
const INDEX_MAGIC: &[u8; 4] = b"UCIX";

/// Save the character index to a binary file.
///
/// Format v5:
/// - [u8; 4]: magic bytes b"UCIX"
/// - u32: format version (4)
/// - u32: feature vector length (FEAT_LEN)
/// - u32: number of characters
/// - For each character:
///   - u32: char as u32
///   - u32: number of font entries
///   - For each entry:
///     - u32: font name length
///     - [u8]: font name bytes
///     - [f32; FEAT_LEN]: raw feature vector
///   - [f32; FEAT_LEN]: per-dimension σ values
/// - u32: number of skipped fonts
/// - For each skipped font:
///   - u32: name length
///   - [u8]: name bytes
pub fn save_index(index: &CharIndex, path: &Path) -> io::Result<()> {
    use std::io::Write;
    let mut buf = Vec::new();

    // Header
    buf.extend_from_slice(INDEX_MAGIC);
    buf.extend_from_slice(&INDEX_VERSION.to_le_bytes());
    buf.extend_from_slice(&(FEAT_LEN as u32).to_le_bytes());

    let n_chars = index.entries.len() as u32;
    buf.extend_from_slice(&n_chars.to_le_bytes());

    for (c, entries) in &index.entries {
        buf.extend_from_slice(&(*c as u32).to_le_bytes());
        buf.extend_from_slice(&(entries.len() as u32).to_le_bytes());
        for e in entries {
            let name_bytes = e.font_name.as_bytes();
            buf.extend_from_slice(&(name_bytes.len() as u32).to_le_bytes());
            buf.extend_from_slice(name_bytes);
            let feat = e.features.as_slice();
            for &v in feat.iter() {
                buf.extend_from_slice(&v.to_le_bytes());
            }
        }
        // Write per-dimension σ for this character
        let sigmas = index.dim_sigmas.get(c)
            .cloned()
            .unwrap_or([0.0f32; FEAT_LEN]);
        for &s in sigmas.iter() {
            buf.extend_from_slice(&s.to_le_bytes());
        }
    }

    // Append skipped_fonts section
    buf.extend_from_slice(&(index.skipped_fonts.len() as u32).to_le_bytes());
    for name in &index.skipped_fonts {
        let name_bytes = name.as_bytes();
        buf.extend_from_slice(&(name_bytes.len() as u32).to_le_bytes());
        buf.extend_from_slice(name_bytes);
    }

    let mut f = std::fs::File::create(path)?;
    f.write_all(&buf)?;
    Ok(())
}

/// Load a character index from a binary file.
pub fn load_index(path: &Path) -> io::Result<CharIndex> {
    use std::io::Read;
    let mut data = Vec::new();
    std::fs::File::open(path)?.read_to_end(&mut data)?;
    let mut pos;

    if data.len() < 12 {
        return Err(io::Error::new(io::ErrorKind::InvalidData, "index file too small"));
    }
    if &data[0..4] != INDEX_MAGIC {
        return Err(io::Error::new(io::ErrorKind::InvalidData,
            "stale index: missing magic header (pre-v2 format)"));
    }
    pos = 4;
    let version = u32::from_le_bytes(data[pos..pos+4].try_into().unwrap());
    pos += 4;
    if version != INDEX_VERSION {
        return Err(io::Error::new(io::ErrorKind::InvalidData,
            format!("stale index: version {version}, expected {INDEX_VERSION}")));
    }
    let feat_len = u32::from_le_bytes(data[pos..pos+4].try_into().unwrap());
    pos += 4;
    if feat_len as usize != FEAT_LEN {
        return Err(io::Error::new(io::ErrorKind::InvalidData,
            format!("stale index: feat_len {feat_len}, expected {FEAT_LEN}")));
    }

    let read_u32 = |pos: &mut usize| -> io::Result<u32> {
        if *pos + 4 > data.len() {
            return Err(io::Error::new(io::ErrorKind::UnexpectedEof, "truncated"));
        }
        let v = u32::from_le_bytes(data[*pos..*pos + 4].try_into().unwrap());
        *pos += 4;
        Ok(v)
    };
    let read_f32 = |pos: &mut usize| -> io::Result<f32> {
        if *pos + 4 > data.len() {
            return Err(io::Error::new(io::ErrorKind::UnexpectedEof, "truncated"));
        }
        let v = f32::from_le_bytes(data[*pos..*pos + 4].try_into().unwrap());
        *pos += 4;
        Ok(v)
    };

    let n_chars = read_u32(&mut pos)?;
    let mut entries: HashMap<char, Vec<FontCharEntry>> = HashMap::new();
    let mut dim_sigmas: HashMap<char, [f32; FEAT_LEN]> = HashMap::new();

    for _ in 0..n_chars {
        let c_u32 = read_u32(&mut pos)?;
        let c = char::from_u32(c_u32).ok_or_else(|| {
            io::Error::new(io::ErrorKind::InvalidData, "invalid char")
        })?;
        let n_fonts = read_u32(&mut pos)?;
        let mut font_entries = Vec::with_capacity(n_fonts as usize);

        for _ in 0..n_fonts {
            let name_len = read_u32(&mut pos)? as usize;
            if pos + name_len > data.len() {
                return Err(io::Error::new(io::ErrorKind::UnexpectedEof, "truncated name"));
            }
            let font_name = String::from_utf8_lossy(&data[pos..pos + name_len]).to_string();
            pos += name_len;

            let mut profile = [0.0f32; PROFILE_BINS];
            for p in &mut profile {
                *p = read_f32(&mut pos)?;
            }
            let aspect = read_f32(&mut pos)?;
            let ink_density = read_f32(&mut pos)?;
            let v_center = read_f32(&mut pos)?;
            let h_balance = read_f32(&mut pos)?;
            let serif_score = read_f32(&mut pos)?;
            let stroke_contrast = read_f32(&mut pos)?;
            let xh_cap_ratio = read_f32(&mut pos)?;

            // v2 features
            let counter_area_ratio = read_f32(&mut pos)?;
            let counter_centroid_x = read_f32(&mut pos)?;
            let counter_centroid_y = read_f32(&mut pos)?;
            let counter_aspect = read_f32(&mut pos)?;
            let mut terminal_angles = [0.0f32; TERMINAL_ANGLE_BINS];
            for t in &mut terminal_angles {
                *t = read_f32(&mut pos)?;
            }
            let ink_perimeter = read_f32(&mut pos)?;
            let compactness = read_f32(&mut pos)?;
            let mut h_crossings = [0.0f32; CROSSING_BINS];
            for hc in &mut h_crossings {
                *hc = read_f32(&mut pos)?;
            }

            // v3 features
            let mut row_profile = [0.0f32; ROW_PROFILE_BINS];
            for rp in &mut row_profile {
                *rp = read_f32(&mut pos)?;
            }
            let hole_count = read_f32(&mut pos)?;
            let h_symmetry = read_f32(&mut pos)?;
            let v_symmetry = read_f32(&mut pos)?;
            let skeleton_branch_pts = read_f32(&mut pos)?;
            let skeleton_end_pts = read_f32(&mut pos)?;
            let corner_count = read_f32(&mut pos)?;
            let mut quadrant_density = [0.0f32; 4];
            for qd in &mut quadrant_density {
                *qd = read_f32(&mut pos)?;
            }

            font_entries.push(FontCharEntry {
                font_name,
                features: CharFeatures {
                    profile,
                    row_profile,
                    aspect,
                    ink_density,
                    v_center,
                    h_balance,
                    serif_score,
                    stroke_contrast,
                    xh_cap_ratio,
                    counter_area_ratio,
                    counter_centroid_x,
                    counter_centroid_y,
                    counter_aspect,
                    terminal_angles,
                    ink_perimeter,
                    compactness,
                    h_crossings,
                    hole_count,
                    h_symmetry,
                    v_symmetry,
                    skeleton_branch_pts,
                    skeleton_end_pts,
                    corner_count,
                    quadrant_density,
                },
            });
        }

        // Read per-dimension σ
        let mut sigmas = [0.0f32; FEAT_LEN];
        for s in &mut sigmas {
            *s = read_f32(&mut pos)?;
        }
        dim_sigmas.insert(c, sigmas);

        entries.insert(c, font_entries);
    }

    // Read skipped_fonts section
    let mut skipped_fonts = std::collections::HashSet::new();
    if pos < data.len() {
        if let Ok(n_skipped) = read_u32(&mut pos) {
            for _ in 0..n_skipped {
                let name_len = read_u32(&mut pos)? as usize;
                if pos + name_len > data.len() {
                    return Err(io::Error::new(io::ErrorKind::UnexpectedEof, "truncated skipped font name"));
                }
                let name = String::from_utf8_lossy(&data[pos..pos + name_len]).to_string();
                pos += name_len;
                skipped_fonts.insert(name);
            }
        }
    }

    let mut index = CharIndex {
        entries,
        skipped_fonts,
        font_names_table: Vec::new(),
        flat_vecs: HashMap::new(),
        dim_sigmas,
    };
    // Build flat vecs from loaded entries
    index.rebuild_vecs();
    Ok(index)
}

/// Read just the 12-byte header from a cached index file.
pub fn peek_header(path: &Path) -> io::Result<(u32, u32)> {
    use std::io::Read;
    let mut f = std::fs::File::open(path)?;
    let mut header = [0u8; 12];
    f.read_exact(&mut header)?;

    if &header[0..4] != INDEX_MAGIC {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "missing UCIX magic header",
        ));
    }
    let version = u32::from_le_bytes(header[4..8].try_into().unwrap());
    let feat_len = u32::from_le_bytes(header[8..12].try_into().unwrap());
    Ok((version, feat_len))
}

/// Return the current expected version and feature length.
pub fn expected_header() -> (u32, u32) {
    (INDEX_VERSION, FEAT_LEN as u32)
}

/// Count the number of unique font names across all characters in the index.
pub fn count_fonts(index: &CharIndex) -> usize {
    index.font_names().len()
}

impl CharIndex {
    /// Collect all unique font names known to this index (both indexed and skipped).
    pub fn font_names(&self) -> std::collections::HashSet<String> {
        let mut names = self.skipped_fonts.clone();
        for entries in self.entries.values() {
            for e in entries {
                names.insert(e.font_name.clone());
            }
        }
        names
    }

    /// Collect only the font names that have actual indexed entries (not skipped).
    pub fn indexed_font_names(&self) -> std::collections::HashSet<String> {
        let mut names = std::collections::HashSet::new();
        for entries in self.entries.values() {
            for e in entries {
                names.insert(e.font_name.clone());
            }
        }
        names
    }

    /// Merge another index into this one.
    pub fn merge(&mut self, other: CharIndex) {
        for (c, new_entries) in other.entries {
            let existing = self.entries.entry(c).or_default();
            let existing_names: std::collections::HashSet<String> =
                existing.iter().map(|e| e.font_name.clone()).collect();
            for entry in new_entries {
                if !existing_names.contains(&entry.font_name) {
                    existing.push(entry);
                }
            }
        }
        self.skipped_fonts.extend(other.skipped_fonts);
        // Rebuild vecs after merge
        self.rebuild_vecs();
    }

    /// Remove all entries for the given font names.
    pub fn remove_fonts(&mut self, names: &std::collections::HashSet<String>) {
        for entries in self.entries.values_mut() {
            entries.retain(|e| !names.contains(&e.font_name));
        }
        self.skipped_fonts.retain(|n| !names.contains(n));
        // Rebuild vecs after removal
        self.rebuild_vecs();
    }

    /// Drop the raw `entries` HashMap to free memory after the index has been
    /// saved to disk.  Only `flat_vecs` (used for search) is kept.
    /// After compaction, `save_index` will no longer work — call this only once
    /// the index is persisted and you're entering the search/match phase.
    pub fn compact(&mut self) {
        self.entries.clear();
        self.entries.shrink_to_fit();
    }

    /// Number of indexed characters.
    pub fn n_chars(&self) -> usize {
        self.flat_vecs.len()
    }

    /// Total number of (deduplicated) font entries across all characters.
    pub fn n_entries(&self) -> usize {
        self.flat_vecs.values().map(|v| v.len()).sum()
    }
}
